equinor/fusion-framework

- package-lock.json
- packages/module-telemetry/src/provider.ts
- packages/module/package.json
- packages/module/src/initialize-modules.ts
- packages/module/src/types.ts
- delay initializing of module until dependent module is loaded
- add logging
> feat(module): allow modules to have deps

- .husky/pre-commit
- package-lock.json
- package.json
- packages/module-ag-grid/package.json
- packages/module-ag-grid/src/configurator.ts
- packages/module-ag-grid/src/index.ts
- packages/module-ag-grid/src/module.ts
- packages/module-ag-grid/src/provider.ts
- packages/module-ag-grid/tsconfig.json
initial module for setting license key in ag grid
> Module for AG Grid

- packages/observable/jest.config.js
- packages/observable/src/ReactiveObservable.ts
- packages/observable/src/__tests__/Query.test.ts
- packages/observable/src/__tests__/QueryClient.test.ts
- packages/observable/src/__tests__/ReactiveObservable.test.ts
- packages/observable/src/__tests__/useObservableEpic.test.ts
- packages/observable/src/__tests__/useObservableInput.test.ts
- packages/observable/src/__tests__/useObservableSubscription.test.ts
- packages/observable/src/__tests__/useQueryClient.test.ts
- packages/observable/src/query/Query.ts
- packages/observable/src/query/QueryClient.ts
- packages/observable/src/query/index.ts
- packages/observable/src/react/index.ts
- packages/observable/src/react/useObservableInput.ts
- packages/observable/src/react/useObservableSubscription.ts
- packages/observable/src/react/useQueryClient.ts
WIP: might expose more like ReactQuery, like error and bool for statuses
> feat(observable): create hook for using query client

- packages/react-module/README.md
- packages/react-module/package.json
- packages/react-module/src/ModuleProvider.tsx
- packages/react-module/src/context.ts
- packages/react-module/src/index.ts
- packages/react-module/src/useModules.ts
- packages/react-module/tsconfig.json
- create method for creating a `ModuleProvider`compoent
- create hook for accessing modules
- create hook for accessing single module
> feat(react-module): initial

- packages/module-event/README.md
- packages/module-event/package.json
- packages/module-event/src/configurator.ts
- packages/module-event/src/dispatcher.ts
- packages/module-event/src/event.ts
- packages/module-event/src/index.ts
- packages/module-event/src/module.ts
- packages/module-event/src/provider.ts
- packages/module-event/tsconfig.json
+ create event configurator
+ create event dispatcher
+ create event provider
+ configure event module
+ create initial documentation
> feat(module-event): initial

- packages/framework/package.json
- packages/framework/src/index.ts
- packages/framework/src/modules.ts
- packages/framework/tsconfig.json
* enable event module in framework
* define event for framework load event
* dispatch event when framework is loaded
* __enable init of additional modules provided__
> feat(framework): enable event module

- packages/module-event/src/event.ts
- packages/module-event/src/index.ts
- packages/react-module-event/package.json
- packages/react-module-event/src/index.ts
- packages/react-module-event/src/useEventHandler.ts
- packages/react-module-event/tsconfig.json
> Feat:(react-module-event): initial

- lerna.json
- package.json
- packages/app/package.json
- packages/framework/package.json
- packages/module-app-config/package.json
- packages/module-http/package.json
- packages/module-http/src/client-msal.ts
- packages/module-http/src/client.ts
- packages/module-msal/package.json
- packages/module-service-discovery/package.json
- packages/module-service-discovery/src/client.ts
- packages/react-app/package.json
- yarn.lock
> feat!: rename fetch method

- packages/module/src/configurator.ts
- packages/module/src/types.ts
when initializing a module, expose a function for checking if a module is added
> feat(module): add has module check

- packages/app/package.json
- packages/framework-react/package.json
- packages/framework/package.json
- packages/module-ag-grid/package.json
- packages/module-app/package.json
- packages/module-http/package.json
- packages/module-msal/package.json
- packages/module-service-discovery/package.json
- packages/module-services/package.json
- packages/module-telemetry/package.json
- packages/module/package.json
- packages/observable/package.json
- packages/react-app/package.json
- packages/react-module-app-config/package.json
- packages/react-module-event/package.json
- packages/react-module-http/package.json
- packages/react-module/package.json
- packages/test-app/package.json
- yarn.lock
@equinor/fusion-framework-module
* @equinor/fusion-framework: ^1.2.2
* @equinor/fusion-framework-app: ^1.2.2
* @equinor/fusion-framework-module-ag-grid: ^1.2.2, ^1.2.2
* @equinor/fusion-framework-module-app: ^1.2.2
* @equinor/fusion-framework-module-app-config: ^1.2.2
* @equinor/fusion-framework-module-event: ^1.2.2
* @equinor/fusion-framework-module-http: ^1.2.2
* @equinor/fusion-framework-module-msal: ^1.2.2
* @equinor/fusion-framework-module-service-discovery: ^1.2.2
* @equinor/fusion-framework-module-services: ^1.1.3 → ^1.2.2, ^1.1.3 → ^1.2.2
* @equinor/fusion-framework-module-telemetry: ^1.2.2
* @equinor/fusion-framework-react-app: ^1.2.2
* @equinor/fusion-framework-react-module: ^1.2.2
@equinor/fusion-framework-module-http
* @equinor/fusion-framework: ^2.0.10
* …
> chore: update deps

- packages/module-services/src/bookmarks/api-models.ts
- packages/module-services/src/bookmarks/client.ts
- packages/module-services/src/bookmarks/get/client.ts
- packages/module-services/src/bookmarks/get/generate-endpoint.ts
- packages/module-services/src/bookmarks/get/generate-parameters.ts
- packages/module-services/src/bookmarks/get/index.ts
- packages/module-services/src/bookmarks/get/types.ts
- packages/module-services/src/bookmarks/index.ts
- packages/module-services/src/bookmarks/types.ts
- packages/module-services/src/index.ts
- packages/module-services/src/provider.ts
- packages/test-app/src/pages/service-bookmarks/GetBookmark.tsx
- packages/test-app/src/pages/service-bookmarks/useBookmarksClient.ts
- packages/test-app/src/pages/service-context/useContextClient.ts
- packages/test-app/src/router.tsx
- vue-press/src/.vuepress/sidebar.ts
- vue-press/src/modules/services/README.md
- vue-press/src/modules/services/bookmarks.md
Added a module-services bookmarks module. Only get for now. Also added a test in test-app to prove it works
> feat(module-services): bookmarks get

- packages/module/src/types.ts
expose type for resolving all types of modules in an array
> fix(module): update typing

- packages/module-services/src/bookmarks/client.ts
- packages/module-services/src/bookmarks/post/client.ts
- packages/module-services/src/bookmarks/post/generate-endpoint.ts
- packages/module-services/src/bookmarks/post/generate-parameters.ts
- packages/module-services/src/bookmarks/post/index.ts
- packages/module-services/src/bookmarks/post/types.ts
- packages/test-app/src/pages/service-bookmarks/PostBookmark.tsx
- packages/test-app/src/router.tsx
Post bookmark method added to module-services bookmarks client
> feat: :sparkles: post bookmark module-services

- packages/module-http/src/lib/selectors/json-selector.ts
- packages/module-services/src/bookmarks/client.ts
- packages/module-services/src/bookmarks/delete/client.ts
- packages/module-services/src/bookmarks/delete/generate-endpoint.ts
- packages/module-services/src/bookmarks/delete/generate-parameters.ts
- packages/module-services/src/bookmarks/delete/index.ts
- packages/module-services/src/bookmarks/delete/types-v1.ts
- packages/module-services/src/bookmarks/delete/types.ts
- packages/test-app/src/pages/service-bookmarks/DeleteBookmark.tsx
- packages/test-app/src/router.tsx
Added bookmark delete in module-services. Added test in test app
closes #340
> feat: :sparkles: module services delete bookmark

- cookbooks/app-react/app.config.js
- cookbooks/app-react/package.json
- packages/cli/package.json
- packages/cli/src/dev-portal/AppLoader.tsx
- packages/cli/src/dev-portal/ErrorViewer.tsx
- packages/cli/src/dev-portal/Router.tsx
- packages/cli/src/dev-portal/config.ts
- packages/cli/src/dev-portal/main.tsx
- packages/cli/src/scripts/app-config.ts
- packages/cli/src/scripts/create-config.ts
- packages/cli/src/scripts/main.ts
- packages/cli/src/scripts/serve.ts
- packages/cli/vite.config.ts
- packages/module-app/src/provider.ts
- packages/observable/src/query/Query.ts
- packages/observable/src/query/client/epics.ts
- yarn.lock
> Feat(cli): portal routing

- packages/module-context/src/configurator.ts
- packages/module-context/src/index.ts
- packages/module-context/src/provider.ts
+ add config option for filter and types
+ resolve parent service if not configured
+ add query function on provider
> feat(module-context): allow query filter

- packages/cli/src/scripts/serve.ts
fix import path of relative files on dev server
closes #431
> fix(cli): relative path resolve

- cookbooks/app-react-context/package.json
- cookbooks/app-react-router/package.json
- packages/app/package.json
- packages/cli/package.json
- packages/framework-react/package.json
- packages/framework/package.json
- packages/module-ag-grid/package.json
- packages/module-app/package.json
- packages/module-http/package.json
- packages/module-msal/package.json
- packages/module-navigation/package.json
- packages/module-service-discovery/package.json
- packages/module-telemetry/package.json
- packages/module/package.json
- packages/react-app/package.json
- packages/react-module-app-config/package.json
- packages/react-module-context/package.json
- packages/react-module-event/package.json
- packages/react-module-http/package.json
- packages/react-module/package.json
- packages/test-app/package.json
- utils/observable/package.json
- yarn.lock
@equinor/fusion-framework-module
* @equinor/fusion-framework: ^1.2.9
* @equinor/fusion-framework-app: ^1.2.9
* @equinor/fusion-framework-module-ag-grid: ^1.2.9, ^1.2.2 → ^1.2.9
* @equinor/fusion-framework-module-app: ^1.2.9
* @equinor/fusion-framework-module-app-config: ^1.2.9
* @equinor/fusion-framework-module-context: ^1.2.9, ^1.2.5 → ^1.2.9
* @equinor/fusion-framework-module-event: ^1.2.9
* @equinor/fusion-framework-module-http: ^1.2.9
* @equinor/fusion-framework-module-msal: ^1.2.9
* @equinor/fusion-framework-module-navigation: ^1.2.9, ^1.2.2 → ^1.2.9
* @equinor/fusion-framework-module-service-discovery: ^1.2.9
* @equinor/fusion-framework-module-services: ^1.2.9, ^1.2.2 → ^1.2.9
* @equinor/fusion-framework-module-telemetry: ^1.2.9
* @equinor/fusion-framework-react-module: ^1.2.9 …
> Update 9 dependencies

- package.json
- utils/observable/src/create-action.ts
- utils/observable/src/index.ts
- utils/observable/src/types/actions.ts
- utils/observable/src/types/flow.ts
- utils/observable/src/types/index.ts
- utils/observable/src/types/observable.ts
- utils/observable/src/types/reducer.ts
- utils/observable/src/types/ts-helpers.ts
- utils/query/src/cache/QueryCache.ts
- utils/query/src/cache/actions.ts
- utils/query/src/client/QueryClient.ts
- utils/query/src/client/actions.ts
* create function for creating action creators
* update typing
* fix typing changes in query
> feat(observable): expose function for creating actions

- utils/observable/src/create-reducer.ts
- utils/observable/src/types/index.ts
- utils/observable/src/types/reducers.ts
* supports `immer`
* dynamic case creator
* dynamic matcher
inspiration from redux-toolkit
> feat(observable): expose functionality for creating a reducer

- utils/observable/src/action-mapper.ts
map action definitions to a object, which executes the call on a subject
> feat(observable): support mapping of action definitions

- utils/observable/src/action-mapper.ts
- utils/observable/src/create-state.ts
function should return:
- created actions
- dispatcher of actions
- subject which holds state
> feat(observable): add functionality for create state

- packages/react-module-context/src/useCurrentContext.ts
> fix: :bug: context undefined on first render

- .gitignore
- package.json
- packages/legacy-interopt/package.json
- packages/legacy-interopt/src/LegacyAppContainer.ts
- packages/legacy-interopt/src/LegacyAuthContainer.ts
- packages/legacy-interopt/src/LegacyAuthUser.ts
- packages/legacy-interopt/src/LegacyContextManager.ts
- packages/legacy-interopt/src/components/LegacyFusionWrapper.tsx
- packages/legacy-interopt/src/components/create-legacy-context-component.tsx
- packages/legacy-interopt/src/components/index.ts
- packages/legacy-interopt/src/create-fusion-context.ts
- packages/legacy-interopt/src/create-service-resolver.ts
- packages/legacy-interopt/src/index.ts
- packages/legacy-interopt/src/legacy-api-signin.ts
- packages/legacy-interopt/src/static.ts
- packages/legacy-interopt/src/types.ts
- packages/legacy-interopt/tsconfig.json
- yarn.lock
create a package for interopt between framework and fusion-api
> feat(legacy-interopt): legacy interopt package

- packages/react/framework/src/app/index.ts
exports hooks useApp and useAppProvider
> fix(framework-app): exporting hooks useApps and useAppProvider

- packages/react/framework/src/app/useApps.ts
Hook should have optional args
> fix(framework-react): make params for useApps optional

- packages/react/framework/src/app/useApps.ts
changes useApps to hide hidden apps.
> fix(useApps): hiding hidden apps

- packages/modules/navigation/src/navigator.ts
- packages/react/legacy-interopt/src/LegacyContextManager.ts
LegacyInterOpt: Moose removal.
Navigation module: removed unused import
> chore(legacy): src cleanup

- cookbooks/app-react-context/package.json
- cookbooks/app-react-people/package.json
- cookbooks/app-react-router/package.json
- cookbooks/app-react/package.json
- package.json
- packages/app/package.json
- packages/cli/package.json
- packages/framework/package.json
- packages/modules/context/package.json
- packages/modules/context/src/client/ContextClient.ts
- packages/react/app/package.json
- packages/react/framework/package.json
- packages/react/legacy-interopt/package.json
- packages/react/legacy-interopt/src/LegacyContextManager.ts
- packages/react/modules/context/package.json
- packages/test-app/package.json
- packages/widget/package.json
Also:
- removed ensureCurrentContextExistsInUrl since unused.
- removed Navigationmodule since unused.
> fix(legacyContext): removed navigation on context change

- cookbooks/app-react/app.config.js
- packages/cli/src/scripts/app-config.ts
- packages/cli/src/scripts/main.ts
- packages/cli/src/scripts/serve.ts
allow setting proxy portal host
> feat(cli): allow configuring portal host in cli

- packages/modules/bookmark/src/configurator.ts
- packages/react/modules/bookmark/package.json
- packages/react/modules/bookmark/src/portal/useBookmarkNavigate.ts
Remove navigation provider resolver sins it not in use
> fix(bookmark-module): remove navigation provider resolver

- cookbooks/app-react-bookmark-advanced/package.json
- cookbooks/app-react-bookmark/package.json
- cookbooks/app-react-bookmark/src/Create.tsx
- cookbooks/app-react/app.config.js
- packages/modules/bookmark/src/client/bookmarkClient.ts
-  shear in cookbook 
- invalidate cache on bookmark update
> fix: bookmark cookbook update

- packages/react/modules/bookmark/src/types.ts
- packages/react/modules/bookmark/src/useBookmark.ts
I forgot to expose getBookmarkById from the useBookmark hook
> fix(bookmark-react-module): allowing for resolving bookmark by id

- packages/modules/services/src/bookmarks/client.ts
- packages/modules/services/src/bookmarks/favorites/delete/client.ts
- packages/modules/services/src/bookmarks/favorites/delete/generate-endpoint.ts
- packages/modules/services/src/bookmarks/favorites/delete/generate-parameters.ts
- packages/modules/services/src/bookmarks/favorites/delete/index.ts
- packages/modules/services/src/bookmarks/favorites/delete/types-v1.ts
- packages/modules/services/src/bookmarks/favorites/delete/types.ts
- packages/modules/services/src/bookmarks/favorites/head/client.ts
- packages/modules/services/src/bookmarks/favorites/head/generate-endpoint.ts
- packages/modules/services/src/bookmarks/favorites/head/generate-parameters.ts
- packages/modules/services/src/bookmarks/favorites/head/index.ts
- packages/modules/services/src/bookmarks/favorites/head/types.ts
- packages/modules/services/src/bookmarks/favorites/post/client.ts
- packages/modules/services/src/bookmarks/favorites/post/generate-endpoint.ts
- packages/modules/services/src/bookmarks/favorites/post/generate-parameters.ts
- packages/modules/services/src/bookmarks/favorites/post/index.ts
- packages/modules/services/src/bookmarks/favorites/post/types.ts
Functionality added:
- Add bookmark to favorites by bookmark id - addFavorite
- Remove bookmark from favorites by bookmark id - removeFavorite
- Verify that the current bookmark is present in the users collection of bookmarks.- verifyFavorite
> feat(bookmark-client): added functionality for bookmark favorites

- packages/modules/bookmark/src/bookmark-provider.ts
- packages/modules/bookmark/src/client/bookmarkClient.ts
- vue-press/src/modules/bookmark/README.md
Bookmark Favorites - Exposing the favorites endpoint from the bookmark api client.
- addBookmarkFavoriteAsync
- removeBookmarkFavoriteAsync
- verifyBookmarkFavoriteAsync
> feat(bookmark-module): added functionality for bookmark favorites

- packages/modules/bookmark/src/bookmark-provider.ts
- packages/modules/bookmark/src/client/bookmarkActions.ts
- packages/modules/bookmark/src/client/bookmarkClient.ts
- packages/modules/bookmark/src/types.ts
- packages/modules/services/src/bookmarks/client.ts
- packages/modules/services/src/bookmarks/patch/client.ts
- packages/modules/services/src/bookmarks/patch/generate-endpoint.ts
- packages/modules/services/src/bookmarks/patch/generate-parameters.ts
- packages/modules/services/src/bookmarks/patch/index.ts
- packages/modules/services/src/bookmarks/patch/types.ts
- packages/react/modules/bookmark/src/types.ts
- packages/react/modules/bookmark/src/useBookmark.ts
- vue-press/src/modules/bookmark/README.md
allow for patrial bookmark sent to the patch bookmark function.
> feat(bookmark modules) partial patch bookmark

- cookbooks/app-react-context/src/App.tsx
- cookbooks/app-react-context/src/useRelatedContext.ts
- packages/cli/package.json
update cookboks and test related context
> Feat/cookbooks/app react context/related context

- packages/modules/context/src/ContextProvider.ts
- packages/modules/services/src/context/related/types.ts
when failing to resolve context, skip clearing context
> fix(context): skip clearing context

- .github/workflows/release.yml
- packages/modules/telemetry/package.json
Bacon ipsum dolor amet swine spare ribs shankle pork chop, short loin chislic ham hock meatball t-bone biltong shank beef alcatra short ribs leberkas. Kevin biltong frankfurter filet mignon, sausage tail fatback beef. Biltong boudin beef, spare ribs picanha pancetta tongue kielbasa swine alcatra jowl t-bone fatback rump. Corned beef beef rump tail cow meatball shank short loin. Ball tip tri-tip beef ribs, burgdoggen bacon tenderloin tail pork chop landjaeger bresaola buffalo jerky tongue. Ham hock pork belly salami porchetta meatball t-bone drumstick.
> chore: update release action

- .github/workflows/release-pr.yml
T-bone pork loin chicken ground round shankle, pork chop alcatra burgdoggen. Andouille picanha chislic shank rump landjaeger flank kielbasa jerky. Turkey turducken salami short loin doner ham hock. Shankle kielbasa sausage sirloin rump beef, alcatra filet mignon. Shank fatback porchetta flank tail. Pork loin picanha burgdoggen, alcatra boudin chicken fatback cupim porchetta rump ham hock filet mignon tri-tip shoulder ball tip.
> fix: update release-action

- .github/workflows/release-pr.yml
Beef jerky burgdoggen t-bone leberkas, pancetta shank shoulder tri-tip capicola chislic salami meatball. Meatball pork loin sausage venison burgdoggen pork belly rump cupim swine flank jowl bresaola leberkas boudin. Doner short loin alcatra beef drumstick jowl sausage tongue buffalo strip steak. Chislic landjaeger fatback corned beef shank tenderloin beef boudin chicken salami kevin beef ribs hamburger. Tri-tip strip steak short ribs cow rump boudin spare ribs.
> Test - release action

- .github/workflows/release-pr.yml
- packages/modules/telemetry/package.json
Bacon ipsum dolor amet swine spare ribs shankle pork chop, short loin chislic ham hock meatball t-bone biltong shank beef alcatra short ribs leberkas. Kevin biltong frankfurter filet mignon, sausage tail fatback beef. Biltong boudin beef, spare ribs picanha pancetta tongue kielbasa swine alcatra jowl t-bone fatback rump. Corned beef beef rump tail cow meatball shank short loin. Ball tip tri-tip beef ribs, burgdoggen bacon tenderloin tail pork chop landjaeger bresaola buffalo jerky tongue. Ham hock pork belly salami porchetta meatball t-bone drumstick.
Landjaeger picanha ribeye, ball tip cow pork chop chicken chislic shoulder filet mignon ham hock swine tri-tip pig hamburger. Landjaeger venison bresaola cupim tenderloin strip steak fatback ball tip pork chop. Frankfurter picanha turducken, …
> test - update release action

- .github/workflows/release-pr.yml
- packages/modules/telemetry/package.json
Bacon ipsum dolor amet meatball corned beef shankle doner hamburger bresaola sirloin, ground round boudin. Biltong pig frankfurter, pork chop ham hock boudin capicola burgdoggen fatback brisket filet mignon short ribs. T-bone buffalo leberkas strip steak pork loin, bresaola filet mignon. Short loin ribeye salami picanha hamburger pork chop spare ribs capicola pastrami shoulder. Fatback landjaeger ball tip turkey, corned beef drumstick burgdoggen jowl. Pork pork loin pork chop tail.
Strip steak bresaola turducken drumstick, shoulder shank leberkas doner chicken capicola pork belly. Cupim cow kielbasa fatback buffalo chuck kevin sausage pork chop bacon jowl. Tri-tip tail turkey jowl ground round salami buffalo short loin bacon corned beef chislic. Kevin burgdoggen boudin leberkas flank, …
> Test - release action 2

- packages/cli/src/dev-portal/AppLoader.tsx
- packages/cli/src/dev-portal/ContextSelector.tsx
- packages/cli/src/dev-portal/main.tsx
- packages/cli/src/scripts/app-config.ts
- packages/modules/navigation/src/module.ts
> chore: fixing general linting warnings

- packages/modules/services/src/provider.ts
> fix(services): update-api-provider-types

- .github/workflows/release-pr.yml
- packages/modules/telemetry/package.json
Bacon ipsum dolor amet filet mignon short loin turducken, flank meatloaf shank chicken jerky kevin tail porchetta andouille meatball strip steak pancetta. Capicola leberkas ham hock bresaola biltong sausage. Tenderloin capicola t-bone biltong short ribs pancetta fatback pig jerky ham pork loin drumstick strip steak shoulder. Salami boudin pork loin short loin, brisket porchetta prosciutto sausage rump tongue landjaeger hamburger. Pork loin bacon pig shank bresaola meatloaf ground round. Jerky drumstick shank, doner pork loin beef ham boudin flank brisket venison tenderloin hamburger capicola.
Rump pork loin shankle fatback capicola pig flank sirloin chislic meatloaf turkey cupim. Buffalo turducken ball tip tri-tip. Short loin shoulder pig doner kielbasa, burgdoggen biltong leberkas. Ball …
> test - update github action

- packages/modules/ag-grid/package.json
> chore: update ag-grid version

- cookbooks/app-react-people/src/App.tsx
- cookbooks/app-react-people/src/api-models.ts
- cookbooks/app-react-router/src/Router.tsx
- package.json
Also fixes minor lint errors in the cookbooks.
> chore: add lint for cookbooks

- packages/modules/context/src/ContextProvider.ts
after aligning the `setCurrentContext` to an observable, the event listener did not subscribe, which did not execute the function.
[.subscribe((context) => this.#contextClient.setCurrentContext(context ?? null))](https://github.com/equinor/fusion-framework/blob/3cd1a9e01c56fc9afb72f2df474a7b066b4215c4/packages/modules/context/src/ContextProvider.ts#L181)
- add queue for setting context
- add wrapper for queue executor
_functionality around setting context has gotten rather complex to handle all uses cases, this might be refactor in the future_
> setting context is an observable since the functionality does not execute immediately, example resolving related context and validate threw callbacks.
>
> this function needed a queue since one can never trust the developer to await setting of …
> fix(module-context): execute all setting of context

- vue-press/src/guide/app/legacy.md
+ add example for React Router 5
> docs(guid): update docs for legacy router

- packages/react/modules/bookmark/package.json
- packages/react/modules/bookmark/src/types.ts
- packages/react/modules/bookmark/src/useBookmark.ts
quick and dirty check
@TODO refactor `useBookmark`
> fix(react-module-bookmark): check if bookmark provider

- .changeset/happy-eyes-arrive.md
- .changeset/old-planets-hear.md
- packages/modules/module/package.json
- packages/modules/module/src/lib/index.ts
- packages/modules/module/src/lib/provider/BaseModuleProvider.ts
- packages/modules/module/src/lib/provider/index.ts
- packages/modules/module/tsconfig.json
- packages/modules/navigation/src/lib/provider/NavigationProvider.ts
> Update module provider behavior

- .changeset/spicy-days-nail.md
- packages/react/legacy-interopt/src/LegacyAppContainer.ts
compare less features between manifest.
closes:
> fix(legacy-iteropt): prevent legacy death spiral

- .changeset/flat-bulldogs-return.md
- .changeset/light-comics-bow.md
- .changeset/long-bottles-march.md
- cookbooks/app-react-router/src/Router.tsx
- packages/react/app/package.json
- packages/react/app/src/navigation/index.ts
- packages/react/app/src/navigation/useNavigationModule.ts
- packages/react/app/src/navigation/useRouter.ts
- packages/react/app/src/useAppModule.ts
- packages/react/app/tsconfig.json
simplify process for using Fusion Framework navigation
closes:
> expose navigation hooks for `@equinor/fusion-framework-react-app`

- .changeset/calm-turtles-shout.md
- .changeset/cyan-lions-smell.md
- .changeset/rotten-mangos-attend.md
- .changeset/shaggy-berries-invite.md
- .changeset/sharp-cameras-help.md
- .changeset/sixty-news-beam.md
- .changeset/sixty-seahorses-swim.md
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/teams-pr.yml
- CONTRIBUTING.md
- cookbooks/app-react-bookmark-advanced/package.json
- cookbooks/app-react-bookmark/package.json
- cookbooks/app-react-context/package.json
- cookbooks/app-react-module/package.json
- cookbooks/app-react-people/package.json
- cookbooks/app-react-router/package.json
- cookbooks/app-react/package.json
- package.json
- packages/modules/navigation/package.json
- packages/react/framework/src/create-framework-provider.tsx
- packages/utils/observable/src/react/useObservableRef.ts
- packages/utils/query/package.json
- yarn.lock
[release failing](https://github.com/equinor/fusion-framework/actions/runs/5218475968) because since it did not install devDependencies.
https://github.com/equinor/fusion-framework/blob/d11a5796b5932ee6f1b5ed3eca9672bf2f9bd526/.github/workflows/release.yml#L30
* fix linting errors
* update uuid (broken build)
> Chore: refactor and update

- .changeset/perfect-shoes-fry.md
- cookbooks/app-react-bookmark-advanced/package.json
- cookbooks/app-react-bookmark/package.json
- cookbooks/app-react-context/package.json
- cookbooks/app-react-module/package.json
- cookbooks/app-react-people/package.json
- cookbooks/app-react-router/package.json
- cookbooks/app-react/package.json
> fix(cookbooks): remove leading `/` in package's main prop

- .changeset/grumpy-lies-hear.md
- .changeset/perfect-rats-mate.md
- packages/react/legacy-interopt/src/LegacyAppContainer.ts
- packages/react/legacy-interopt/src/create-legacy-render.tsx
some legacy application did not always resolve initial context route
closes:
> issues with legacy current app manifest

- .changeset/purple-bears-burn.md
- cookbooks/app-react-bookmark-advanced/package.json
- cookbooks/app-react-router/package.json
- packages/modules/navigation/package.json
- yarn.lock
@remix-run/router
* @equinor/fusion-framework-cookbook-app-react-bookmark-advanced: ^1.3.3 → ^1.7.2
* @equinor/fusion-framework-cookbook-app-react-router: ^1.0.4 → ^1.7.2
* @equinor/fusion-framework-module-navigation: ^1.6.1 → ^1.7.2, ^1.6.1 → ^1.7.2
* react-router: 1.6.2 → ^1.7.2
* react-router-dom: 1.6.2 → ^1.7.2
closes: #1051 
> Update dependency: @remix-run/router@^1.7.2

- .changeset/shaggy-cows-divide.md
- cookbooks/app-react-ag-grid/package.json
- packages/modules/ag-grid/package.json
- yarn.lock
@ag-grid-community/client-side-row-model
* @equinor/fusion-framework-cookbook-app-react-ag-grid: ^29.3.5 → ~30.0.5
@ag-grid-community/core
* @equinor/fusion-framework-cookbook-app-react-ag-grid: ^29.3.5 → ~30.0.5
@ag-grid-community/react
* @equinor/fusion-framework-cookbook-app-react-ag-grid: ^29.3.5 → ~30.0.5
@ag-grid-enterprise/core
* @equinor/fusion-framework-module-ag-grid: ~29.3.4 → ~30.0.5
closes: #1052 #1050 #1049
> chore: update ag-grid to ~30.0

- .github/workflows/generate-docs.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
add cache for node for github actions
> chore: update workflows

- .changeset/dry-parents-design.md
- .changeset/light-cows-play.md
- packages/modules/event/src/provider.ts
- packages/react/modules/event/src/index.ts
- packages/react/modules/event/src/useEventStream.ts
- packages/react/modules/event/src/useModulesEventProvider.ts
- vue-press/src/.vuepress/sidebar.ts
- vue-press/src/modules/event/README.md
- vue-press/src/modules/event/react.md
create hook for observing events
> does not change any existing functionality
closes:
> Feat(modules-event-event): create hook for observing events

- .changeset/nervous-mugs-prove.md
- packages/react/modules/bookmark/src/types.ts
> fix(bookmark-react): update CreateBookMarkFn type to support promise

- .github/workflows/actions/clear-cache/action.yml
> chore: fix workflow action

- .github/workflows/actions/clear-cache/action.yml
> chore: fix action gh token

- .github/workflows/actions/clear-cache/action.yml
- .github/workflows/actions/clear-cache/clear-cache.sh
> chore: chore/action-clear-cache-plugin

- .changeset/mean-steaks-exercise.md
- .npmrc
- package.json
- packages/cli/.gitignore
- packages/cli/.npmignore
- packages/cli/bin/cli.mjs
- packages/cli/package.json
- packages/cli/tsconfig.json
- packages/cli/vite.config.ts
removes preinstall quirk for bin files which are not built in packages yet
> fix(cli): fix bin resolve of cli

- .changeset/large-ducks-sit.md
- cookbooks/app-react-ag-grid/package.json
- packages/modules/ag-grid/package.json
- pnpm-lock.yaml
__maintaines__
update Ag Grid to 30.1
> chore: update ag-grid

- .changeset/fresh-pumpkins-rescue.md
- cookbooks/app-react-context/package.json
- cookbooks/app-react-context/src/config.ts
- cookbooks/app-react-context/src/useRelatedContext.ts
- cookbooks/app-react-context/tsconfig.json
update typing in context cookbook after improvements of #1099 
closes: #1212 
> fix(cookbook-app-react-context): update types

- packages/modules/services/package.json
- packages/modules/services/src/people/api-models.ts
- packages/modules/services/src/people/index.ts
> fix(module-services): export sub packages

- .changeset/wicked-rivers-divide.md
- packages/modules/services/src/people/api-models.ts
- packages/modules/services/src/people/api-models.v2.ts
- packages/modules/services/src/people/api-models.v4.ts
- packages/modules/services/src/people/client.ts
- packages/modules/services/src/people/person-details/client.ts
- packages/modules/services/src/people/person-details/generate-endpoint.ts
- packages/modules/services/src/people/person-details/types.ts
- packages/modules/services/src/people/person-photo/client.ts
- packages/modules/services/src/people/person-photo/generate-endpoint.ts
- packages/modules/services/src/people/person-photo/types.ts
- packages/modules/services/src/people/query/client.ts
- packages/modules/services/src/people/query/types.ts
- update people service api models
- resolve expansion of person detail query
> feat(module-services): update api models

- vue-press/src/modules/context/README.md
I've been searching the docs and code for valid list of context types. When I finally found an endpoint giving the answer, I though it would be nice to add to the docs for others that might be looking for the same...
> Update docs for setContextType

- .changeset/hot-pants-rule.md
- cookbooks/app-react/src/App.tsx
- packages/cli/src/bin/dev-portal/AppLoader.tsx
- packages/cli/src/index.tsx
closes:
To be able to use height 100% and support ag-grid displaying fullscreen.
> chore: application element height fix

- vue-press/src/modules/http/README.md
> docs: replace convince with convince

- .changeset/cool-olives-smell.md
- .gitignore
- cookbooks/app-react-people/app.manifest.config.ts
- cookbooks/app-react-people/package.json
- cookbooks/app-react-people/src/App.tsx
- cookbooks/app-react-people/src/Router.tsx
- cookbooks/app-react-people/src/config.ts
- cookbooks/app-react-people/src/pages/AvatarPage.tsx
- cookbooks/app-react-people/src/pages/CardPage.tsx
- cookbooks/app-react-people/src/pages/HomePage.tsx
- cookbooks/app-react-people/src/pages/ListItemPage.tsx
- cookbooks/app-react-people/src/pages/SelectorPage.tsx
- cookbooks/app-react-people/src/routes.tsx
- cookbooks/app-react-people/tsconfig.json
- cookbooks/app-react/tsconfig.json
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
- vue-press/package-lock.json
- vue-press/package.json
- vue-press/src/.vuepress/sidebar.ts
- vue-press/src/guide/app/people.md
- vue-press/src/modules/app/README.md
> add cookbook and documentation for react people components

- .changeset/stale-baboons-fold.md
> fix(cli and people-provider): add missing changeset

- .changeset/chatty-walls-mate.md
- packages/modules/ag-grid/package.json
- pnpm-lock.yaml
> build(module-ag-grid): update @ag-grid-enterprise/core to 30.2.0

- .github/ISSUE_TEMPLATE/bug-report---framework.md
- .github/ISSUE_TEMPLATE/bug-report---implementation.md
- .github/ISSUE_TEMPLATE/bug-report--cli.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
https://github.blog/changelog/2023-08-10-github-issues-projects-august-10th-update/#updates-to-issue-forms
closes:
> chore(github): add projects to issues template

- .changeset/breezy-zebras-add.md
- pnpm-lock.yaml
> build(cli): update deps

- .changeset/shaggy-singers-relate.md
- packages/utils/query/src/Query.ts
> fix(query): enhance task queue

- .changeset/healthy-horses-happen.md
- cookbooks/app-react-router/src/routes.tsx
- packages/modules/navigation/src/configurator.ts
- packages/modules/navigation/src/module.ts
- packages/modules/navigation/src/navigator.ts
- packages/react/components/people-resolver/src/PeopleResolver.tsx
> fix(navigation): prevent duplicate push actions

- .changeset/big-dots-sniff.md
- packages/cli/src/lib/vite-logger.ts
> fix(cli): silent bug for external asset optimizer

- .changeset/swift-bats-drop.md
- packages/cli/src/lib/vite-logger.ts
> fix(cli): log loop

- .changeset/chilly-walls-scream.md
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
ref: [AB#45999](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/45999)
closes:
> build: update fusion-wc-person

- .changeset/shaggy-needles-hammer.md
- packages/modules/app/package.json
- packages/modules/app/src/app/App.ts
- packages/modules/app/src/app/events.ts
Map more app events _(more events for tracking in telemetry)_
closes:
> feat(module-app): expose events

- .changeset/strong-bees-ring.md
- packages/modules/app/src/app/App.ts
> fix(module-app): fix event details

- vue-press/src/guide/app/cli.md
Add tips for app developers to use `"type": "module"` in the package.json file.
> Docs - cli command app pack

- packages/modules/context/src/types.ts
> fix(context): add missing `graphic` and `meta` props

- .changeset/angry-icons-pretend.md
- cookbooks/app-react-ag-grid/package.json
- packages/modules/ag-grid/package.json
- pnpm-lock.yaml
update ag grid to 31.0.1
closes:
> update ag grid to 31

- .github/workflows/ci.yml
- .github/workflows/generate-docs.yml
- package.json
- vue-press/package.json
> chore: update doc workflow

- .changeset/clean-radios-smash.md
- packages/react/framework/src/app/useApps.ts
Propagates error from useApps, so potential crashes / errors can be handled gracefully (e.g no access, missing token or similar)
> feat(react-app): Propagate error

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> doc: update contribute

- .changeset/nine-rabbits-repeat.md
- packages/react/app/package.json
> chore: add missing exported type

- .changeset/wise-ladybugs-change.md
- pnpm-lock.yaml
- vue-press/package.json
- vue-press/src/.vuepress/client.ts
- vue-press/src/.vuepress/theme.ts
> chore(deps): upgrade vuepress to rc 8

- .changeset/early-ghosts-remain.md
- cookbooks/app-react-context/package.json
- packages/cli/package.json
- packages/cli/src/bin/dev-portal/ContextSelector.tsx
- packages/modules/context/package.json
- packages/modules/context/src/ContextProvider.ts
- packages/modules/context/src/errors.ts
- packages/react/components/people-resolver/package.json
- packages/react/modules/context/src/index.ts
- pnpm-lock.yaml
> feat(context): add FusionContextSearchError

- .changeset/olive-starfishes-compare.md
- packages/cli/src/bin/dev-portal/ContextSelector.tsx
Ref [AB#46886](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/46886)
closes:
> fix(contextselector): show message when unhandled error occurs

- .changeset/hot-penguins-own.md
- packages/cli/src/bin/dev-portal/ContextSelector.tsx
> fix(context-selector): add error and info icons

- .changeset/angry-pants-lick.md
- packages/cli/src/bin/dev-portal/ContextSelector.tsx
> fix(context-selector): fix typo

- .changeset/late-experts-try.md
- cookbooks/app-react-people/package.json
- cookbooks/app-react-people/src/App.tsx
- cookbooks/app-react-people/src/Styled.tsx
- cookbooks/app-react-people/src/pages/AvatarPage.tsx
- cookbooks/app-react-people/src/pages/CardPage.tsx
- cookbooks/app-react-people/src/pages/ListItemPage.tsx
- cookbooks/app-react-people/src/pages/Navigation.tsx
- cookbooks/app-react-people/src/pages/SelectorPage.tsx
- cookbooks/app-react-people/src/routes.tsx
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
Updates fwc-person in cli and improves cookbook people
> Updates fwc-person in cli and improves cookbook people

- .changeset/funny-shirts-taste.md
- .changeset/poor-trainers-hear.md
- cookbooks/app-react-context-custom-error/package.json
- cookbooks/app-react-context-custom-error/src/App.tsx
- cookbooks/app-react-context-custom-error/src/config.ts
- cookbooks/app-react-context-custom-error/src/index.ts
- cookbooks/app-react-context-custom-error/tsconfig.json
- pnpm-lock.yaml
- vue-press/src/modules/context/README.md
> add doc and cookbook for custom context error

- .changeset/wicked-bottles-search.md
- packages/cli/package.json
- pnpm-lock.yaml
> chore: removed unused packages

- .changeset/hungry-buses-relate.md
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
> chore(deps): bump @equinor/fusion-wc-person from 2.6.4 to 2.6.5

- pnpm-lock.yaml
> chore(lockfile): update lockfile from previous merge

- .changeset/bright-rings-play.md
- .changeset/fuzzy-beers-learn.md
- cookbooks/app-vanilla/app.manifest.config.ts
- cookbooks/app-vanilla/package.json
- cookbooks/app-vanilla/src/index.ts
- cookbooks/app-vanilla/tsconfig.json
- packages/app/src/types.ts
- pnpm-lock.yaml
add an example for creating an vanilla javascript application
closes:
> feat: create an vanilla cookbook app

- .changeset/real-cougars-hide.md
- cookbooks/app-react-ag-grid/package.json
- packages/modules/ag-grid/package.json
- pnpm-lock.yaml
> chore: update ag-grid to 31.2

- .changeset/happy-foxes-repair.md
- cookbooks/app-react-people/package.json
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
To update all person components in framework
> chore(framework): person component update

- .changeset/real-boats-cry.md
- packages/cli/src/bin/dev-portal/AppLoader.tsx
- packages/cli/src/bin/dev-portal/Router.tsx
- packages/cli/src/bin/dev-portal/index.html
- packages/cli/src/bin/dev-portal/main.tsx
> feat(cli): align dev-portal markup

- .changeset/lucky-candles-play.md
- packages/cli/src/bin/dev-portal/AppLoader.tsx
- packages/cli/src/bin/dev-portal/Router.tsx
> fix(cli): hotfix of #2051

- .changeset/tasty-gifts-whisper.md
- packages/utils/observable/src/FlowSubject.ts
> feat(observable): allow multiple effect triggers

- .changeset/real-queens-help.md
- packages/modules/navigation/src/navigator.ts
- packages/react/app/src/index.ts
- packages/react/app/src/make-component.tsx
> docs: update documentation

- .changeset/swift-parrots-hug.md
- package.json
- packages/cli/package.json
- pnpm-lock.yaml
> chore(deps): bump vite to 5.2.10

- .changeset/slow-spies-pretend.md
- pnpm-lock.yaml
- vue-press/package.json
> chore(deps): bump vue to 3.4.25

- .changeset/chatty-boats-doubt.md
- vue-press/src/guide/app/cookbooks.md
- vue-press/src/modules/context/README.md
- vue-press/src/modules/http/README.md
- vue-press/src/modules/navigation/README.md
> docs: update docs

- .changeset/cool-flies-smile.md
- .changeset/great-buckets-boil.md
- cookbooks/app-react-people/src/App.tsx
- cookbooks/app-react-people/src/pages/ListItemPage.tsx
- cookbooks/app-react-people/src/pages/Navigation.tsx
- packages/cli/src/bin/dev-portal/AppLoader.tsx
This PR introduces the following changes:
- Updates the `@equinor/fusion-framework-cookbook-app-react-people` package to fix the content height issue in the dev portal.
- Updates the `@equinor/fusion-framework-cli` package to fix the styling of the render root element for applications.
Currently, the content height in the dev portal is not adjusted correctly, leading to potential layout issues.
With this PR, the content height in the dev portal for the `@equinor/fusion-framework-cookbook-app-react-people` package is now adjusted correctly, ensuring proper layout and rendering.
Additionally, the styling of the render root element for applications in the `@equinor/fusion-framework-cli` package has been fixed, addressing the issue mentioned in https://github.com/equinor/fusion/issues/301. …
> Fix(cli): portal height

- .changeset/tricky-bags-crash.md
- .changeset/wicked-olives-jog.md
- package.json
- packages/modules/http/package.json
- packages/utils/log/README.md
- packages/utils/log/package.json
- packages/utils/log/src/ConsoleLogger.ts
- packages/utils/log/src/Logger.interface.ts
- packages/utils/log/src/Logger.ts
- packages/utils/log/src/index.ts
- packages/utils/log/src/resolve-log-level.ts
- packages/utils/log/src/static.ts
- packages/utils/log/tests/ConsoleLogger.test.ts
- packages/utils/log/tsconfig.json
- packages/utils/log/vitest.config.ts
- packages/utils/observable/package.json
- packages/utils/query/package.json
- pnpm-lock.yaml
This PR introduces a new package `@equinor/fusion-log` to the `packages/utils` directory. The package provides a set of utilities for logging messages in a TypeScript/JavaScript application within the Fusion Framework. The primary purpose of this code is to provide a consistent and configurable logging mechanism that can be used throughout the application.
The logging utilities in this package are designed to provide a flexible and extensible logging solution. The main components are:
- `Logger` (abstract class): Defines the base interface and functionality for logging messages with different severity levels (debug, info, warn, error).
- `ConsoleLogger`: A concrete implementation of the `Logger` class that logs messages to the console.
- `LogLevel` (enum): Defines the different log levels …
> Feat/fusion log/initial

- .changeset/serious-crews-wonder.md
- cookbooks/app-react-feature-flag/package.json
- cookbooks/app-react-people/package.json
- packages/cli/package.json
- packages/react/components/bookmark/package.json
- pnpm-lock.yaml
Updated the following packages to use the latest version of @equinor/eds-core-react (v0.38.0) and @equinor/eds-utils (v0.8.5):
- @equinor/fusion-framework-react-components-bookmark 
- @equinor/fusion-framework-cookbook-app-react-feature-flag 
- @equinor/fusion-framework-cookbook-app-react-people 
- @equinor/fusion-framework-cli
> feat(deps): update @equinor/eds

- .changeset/cuddly-points-pull.md
- packages/app/src/AppConfigurator.ts
> fix(app): add options to useFrameworkServiceClient

- .changeset/chatty-gorillas-bake.md
- cookbooks/app-react-ag-grid/src/App.tsx
- cookbooks/app-react-ag-grid/src/table/coldef.tsx
- cookbooks/app-react-ag-grid/src/table/sidebar.tsx
code comment in ag grid cookbook
> fix(cookbook): ag grid cookbook comment code

- .changeset/nice-laws-hang.md
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
Update fusion-wc-person to resolve issue with positioning
closes:
> chore: update fusion-wc-person to 2.6.8

- .github/workflows/actions/build-docs/action.yml
- .github/workflows/pr-docs.yml
- .github/workflows/pr.yml
> chore: update workflow for pr

- .changeset/small-fishes-destroy.md
- packages/cli/package.json
- packages/cli/src/bin/dev-portal/ContextSelector/ContextSelector.tsx
- pnpm-lock.yaml
Enhanced ContextSelector component in the CLI package:
- Implemented responsive context clearing mechanism
- Improved handling of context selection and clearing events
- Optimized component rendering with useMemo and useCallback hooks
Reference [AB#54318](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/54318)
> Fix/cli/dev portal/context selector/clear external

- .changeset/fair-geese-shake.md
- packages/utils/observable/src/types/actions.ts
improve type resolve of ActionBaseType
closes: none
> fix(observable): improve type resolve of ActionBaseType

- .changeset/lemon-pens-report.md
- cookbooks/app-react-people/package.json
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
To fix bug when clearing selected person in component:
- Update `fusion-wc-person` in cli and people-resolver 
- Update `fusion-react-person` in cookbook app-react-people
Reference [AB#55369](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/55369)
> Fix/cli/person select/clear

- .changeset/hip-mugs-begin.md
- packages/cli/vite.config.ts
- packages/modules/ag-grid/src/module.ts
- packages/modules/navigation/src/module.ts
> hotfix: reference check navigation module and ag-grid module.

- packages/cli/src/bin/utils/isAppRegistered.ts
> fix(cli): using node fetch in is AppRegistered

- package.json
- packages/cli/bin/cli.mjs
- packages/cli/package.json
- packages/cli/rollup.config.mjs
- packages/cli/src/bin/create-dev-serve.ts
- packages/cli/tsconfig.json
- packages/cli/tsconfig.lib.json
- pnpm-lock.yaml
> refactor(cli): rework cli to support import without type module in package.json

- .changeset/breezy-lizards-leave.md
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
Updated Dependencies:
- Updated @equinor/fusion-wc-person to ^3.0.4 in package.json.
> chore(deps): updated fusion-wc-person

- package.json
- pnpm-lock.yaml
> chore: remove lint-staged and commitlint dependencies from package.json

- .changeset/selfish-llamas-own.md
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
Updated `@equinor/fusion-wc-person` dependency from version `^3.0.5` to `^3.0.6`
> chore(cli): updating fusion-wc-person to 3.0.6

- cookbooks/app-react/src/App.tsx
Remove settings from app-react since we have own cookbook for settings
> fix(cookbooks): remove settings from app-react

- .changeset/warm-lions-cry.md
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
wc-person component update from 3.1.0 to 3.1.1
> Chore/person component/update

- .changeset/gorgeous-kings-compete.md
- packages/modules/event/package.json
- packages/modules/event/src/event.ts
- pnpm-lock.yaml
> refactor(event): simplify event detail handling and remove immer dependency

- .changeset/clever-suns-draw.md
- packages/react/components/people-resolver/src/PersonController.ts
> feat(people-provider): filter out past positions in PersonController

- .changeset/tasty-starfishes-swim.md
- packages/cli/package.json
- pnpm-lock.yaml
Updating `@equinor/fusion-react-context-selector` to get latest wc in dev-portal
> Fix/cli/deps/context selector/searchable dropdown

- .changeset/shaggy-plants-change.md
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
Updating fwc-person to resolve height issues on variant dense
> Fix/deps/fwc person/update

- .changeset/breezy-buses-compare.md
- packages/modules/ag-grid/src/themes.ts
> refactor: remove unused theme properties from fusionTheme

- .changeset/fair-cameras-shake.md
- packages/app/package.json
- packages/react/components/bookmark/package.json
- pnpm-lock.yaml
> fix: update peer dependencies

- cookbooks/app-react/app.manifest.config.ts
> feat: add app manifest definition placeholder in config

- .changeset/eleven-boats-learn.md
- packages/cli/src/bin/dev-portal/useAppContextNavigation.ts
This will align with same behaviour as portal
closes:
> fix(cli): add support for clearing context in cli

- .changeset/small-dragons-try.md
- biome.json
- cookbooks/app-react-ag-grid/src/App.tsx
- cookbooks/app-react-bookmark-advanced/src/Create.tsx
> Feat(biome): use-button-type

- .changeset/big-monkeys-end.md
- biome.json
- packages/cli/src/bin/bundle-application.ts
- packages/cli/src/lib/utils/config.ts
- packages/modules/app/src/AppConfig.ts
- packages/modules/feature-flag/src/FeatureFlagProvider.reducer.ts
- packages/modules/feature-flag/src/FeatureFlagProvider.ts
- packages/modules/feature-flag/src/utils/storage/StorageAdapter.ts
- packages/modules/http/src/lib/operators/capitalize-request-method.operator.ts
- packages/modules/module/src/configurator.ts
- process-turbo-build-log.cjs
replace forEach with for-of loops for better readability
closes:
> refactor: replace forEach with for-of loops for better readability

- .changeset/hungry-laws-shop.md
- biome.json
- packages/react/components/people-resolver/src/PeopleResolverProvider.tsx
> refactor: remove unnecessary React fragments from PeopleResolverProvider

- .changeset/ready-impalas-love.md
- biome.json
- packages/modules/msal/src/v2/client/log/console.ts
- packages/modules/navigation/src/createHistory.ts
- packages/modules/services/src/context/get/generate-endpoint.ts
- packages/modules/services/src/context/query/generate-endpoint.ts
- packages/modules/services/src/context/related/generate-endpoint.ts
- packages/modules/services/src/notification/notification/delete/generate-endpoint.ts
- packages/modules/services/src/notification/notification/get/generate-endpoint.ts
- packages/modules/services/src/notification/notification/getAll/generate-endpoint.ts
- packages/modules/services/src/notification/notification/patch/generate-endpoint.ts
- packages/modules/services/src/notification/notification/post/generate-endpoint.ts
- packages/modules/services/src/notification/settings/get/generate-endpoint.ts
- packages/modules/services/src/notification/settings/put/generate-endpoint.ts
> refactor: remove unnecessary switch cases and update function signatures for clarity

- .changeset/nice-mugs-deny.md
- .changeset/shiny-regions-knock.md
- biome.json
- cookbooks/app-react-ag-grid/src/App.tsx
- cookbooks/app-react-bookmark-advanced/src/Page2.tsx
- cookbooks/app-react-bookmark-advanced/src/Provider.tsx
- cookbooks/app-react-bookmark/src/App.tsx
- cookbooks/app-react-context/src/useRelatedContext.ts
- cookbooks/app-react-people/src/pages/SelectorPage.tsx
- packages/cli/src/bin/dev-portal/AppLoader.tsx
- packages/cli/src/bin/dev-portal/ContextSelector/useContextResolver.ts
- packages/cli/src/bin/dev-portal/PersonSideSheet/index.tsx
- packages/react/app/src/create-legacy-app.tsx
- packages/react/app/src/settings/useAppSetting.ts
- packages/react/app/src/settings/useAppSettings.ts
- packages/react/components/people-resolver/src/PeopleResolver.tsx
- packages/react/legacy-interopt/src/create-legacy-render.tsx
- packages/react/modules/module/src/ModuleProvider.tsx
- packages/react/widget/src/components/BaseWidget.tsx
- packages/utils/observable/src/react/useDebounce.ts
- packages/utils/observable/src/react/useObservableState.ts
- packages/utils/observable/src/react/useObservableSubscription.ts
- packages/utils/observable/tests/react/useObservableSelector.test.ts
> refactor: Conform to Biome `linter.correctness.useExhaustiveDependencies`

- .changeset/salty-lights-boil.md
- biome.json
- packages/utils/query/src/cache/create-reducer.ts
> refactor: Conform to Biome `linter.performance.noDelete`

- .changeset/new-pants-dig.md
- packages/cli/package.json
- pnpm-lock.yaml
Ref [AB#60910](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/60910)
Ref equinor/fusion#524
closes:
> fix(cli): update deps: react-context-selector to 1.0.4

- .changeset/flat-oranges-stay.md
- .changeset/sharp-peaches-act.md
- biome.json
- packages/modules/http/src/configurator.ts
- packages/react/legacy-interopt/src/create-service-resolver.ts
> fix(biome): change useLiteralKeys rule from warn to error

- .changeset/cool-pillows-chew.md
- biome.json
- packages/modules/http/src/provider.ts
- packages/modules/telemetry/src/provider.ts
- packages/modules/widget/src/enable-widget-module.ts
- packages/react/legacy-interopt/src/LegacyAuthContainer.ts
- packages/react/modules/bookmark/src/useBookmark.ts
> refactor: adhere to Biome `useOptionalChain` and improve null checks

- .changeset/tender-papayas-make.md
- biome.json
- packages/modules/module/src/logger.ts
- packages/modules/services/package.json
- packages/modules/services/src/context/index.ts
- packages/modules/services/src/context/query/generate-endpoint.ts
- packages/modules/services/src/context/related/generate-endpoint.ts
- packages/modules/services/tests/context.test.ts
- packages/modules/services/tests/mocks/get-context-item.ts
- packages/modules/services/tests/mocks/index.ts
- packages/modules/services/tests/setup.ts
- packages/modules/services/tsconfig.json
- packages/modules/services/vitest.config.ts
- pnpm-lock.yaml
> Refactor(biome): no accumulating spread

- .changeset/clear-pots-see.md
- biome.json
- packages/cli/src/bin/create-dev-serve.ts
- packages/cli/src/bin/dev-portal/config.ts
- packages/cli/src/lib/plugins/help-proxy/README.md
- packages/cli/src/lib/plugins/help-proxy/help-proxy-plugin.ts
- packages/cli/src/lib/plugins/help-proxy/index.ts
Ref [AB#61038](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/61038)
closes:
> feat(cli): add `help-proxy` plugin for the cli

- .changeset/red-ways-fetch.md
- packages/utils/imports/README.md
- packages/utils/imports/package.json
- packages/utils/imports/src/import-config.ts
- packages/utils/imports/src/import-json.ts
- packages/utils/imports/src/import-script.ts
- packages/utils/imports/src/index.ts
- packages/utils/imports/src/resolve-config-file.ts
- packages/utils/imports/tests/import-config.test.ts
- packages/utils/imports/tests/import-json.test.ts
- packages/utils/imports/tests/import-script.test.ts
- packages/utils/imports/tests/setup.ts
- packages/utils/imports/tsconfig.json
- packages/utils/imports/vitest.config.ts
- pnpm-lock.yaml
Introduce functions for importing scripts and JSON, along with a configuration resolver. Include TypeScript configuration and testing setup. Document usage in README.
> Add utility functions for handling imports and configuration files

- .changeset/chatty-bats-tell.md
- packages/vite-plugins/spa/README.md
- packages/vite-plugins/spa/package.json
- packages/vite-plugins/spa/src/html/bootstrap.ts
- packages/vite-plugins/spa/src/html/index.html.ts
- packages/vite-plugins/spa/src/html/index.ts
- packages/vite-plugins/spa/src/html/register-service-worker.ts
- packages/vite-plugins/spa/src/html/sw.ts
- packages/vite-plugins/spa/src/index.ts
- packages/vite-plugins/spa/src/plugin.ts
- packages/vite-plugins/spa/src/types.ts
- packages/vite-plugins/spa/src/util/load-env.ts
- packages/vite-plugins/spa/src/util/object-to-env.ts
- packages/vite-plugins/spa/tsconfig.json
- pnpm-lock.yaml
This plugin enables building single-page applications (SPAs) with Vite. It provides features such as service discovery, MSAL authentication, and service worker configuration.
- **Service Discovery**: Fetch service discovery configurations and authenticate requests.
- **MSAL Authentication**: Authenticate users with Azure AD.
- **Service Worker**: Intercept fetch requests, apply authentication headers, and rewrite URLs.
- **Custom Templates**: Define custom HTML templates for SPAs.
- **Environment Configuration**: Configure the plugin using `.env` files or programmatically.
```ts
import { defineConfig } from 'vite';
import { plugin as fusionSpaPlugin } from '@equinor/fusion-framework-vite-plugin-spa';
export default defineConfig({
plugins: [fusionSpaPlugin()],
});
```
```ts …
```
> feat(spa-plugin): add initial implementation of Fusion Framework Vite SPA Plugin

- .changeset/red-sloths-find.md
- packages/cli/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
Ref equinor/fusion#551
closes:
> fix(cli): update deps: `@equinor/fusion-wc-person` to 3.1.7

- .changeset/fair-words-wave.md
- packages/modules/ag-grid/package.json
- packages/react/ag-grid/package.json
- pnpm-lock.yaml
Ref equinor/fusion#557
closes:
> fix(ag-grid): update deps: ag-grid-community, ag-grid-enterprise and ag-grid-react to 33.2.4

- .changeset/funny-news-worry.md
- packages/utils/observable/package.json
- packages/utils/observable/src/actions.ts
> feat: add new export for actions in fusion-observable package

- .changeset/plain-results-kiss.md
- packages/utils/load-env/README.md
- packages/utils/load-env/package.json
- packages/utils/load-env/src/env-to-object.ts
- packages/utils/load-env/src/index.ts
- packages/utils/load-env/src/load-env.ts
- packages/utils/load-env/src/object-to-env.ts
- packages/utils/load-env/src/static.ts
- packages/utils/load-env/tests/env-to-object.test.ts
- packages/utils/load-env/tests/load-env.test.ts
- packages/utils/load-env/tests/object-to-env.test.ts
- packages/utils/load-env/tsconfig.json
- packages/utils/load-env/vitest.config.ts
- pnpm-lock.yaml
Introduce a utility package for managing environment variables in Node.js applications, featuring conversion between objects and environment variable strings, loading from .env files, and customizable prefixes. Include tests for core functionalities.
> Initial release of @equinor/fusion-load-env package

- packages/utils/imports/package.json
- packages/utils/imports/tests/setup.ts
> chore: format package.json and update setup.ts to import cwd from node:process

- .changeset/smart-lights-tease.md
- packages/app/package.json
- packages/modules/ag-grid/package.json
- packages/modules/app/package.json
- packages/modules/bookmark/package.json
- packages/modules/event/package.json
- packages/modules/feature-flag/package.json
- packages/modules/http/package.json
- packages/modules/module/package.json
- packages/modules/msal/package.json
- packages/modules/navigation/package.json
- packages/modules/services/package.json
- packages/modules/signalr/package.json
- packages/modules/widget/package.json
- packages/react/ag-grid/package.json
- packages/react/app/package.json
- packages/react/framework/package.json
- packages/react/legacy-interopt/package.json
- packages/react/modules/bookmark/package.json
- packages/react/modules/signalr/package.json
- packages/utils/observable/package.json
- packages/utils/query/package.json
Ref f53b60b7805706ce7617e614f0ac0c24317a2e43
closes:
> fix: re-add typesVersion in package.json files

- .github/workflows/pre-release.yml
> chore(workflow): fixing typo in pre-release inputs

- .changeset/new-msal-node-module.md
- packages/modules/msal-node/README.md
- packages/modules/msal-node/package.json
- packages/modules/msal-node/src/AuthConfigurator.interface.ts
- packages/modules/msal-node/src/AuthConfigurator.ts
- packages/modules/msal-node/src/AuthProvider.interface.ts
- packages/modules/msal-node/src/AuthProvider.ts
- packages/modules/msal-node/src/AuthProviderInteractive.ts
- packages/modules/msal-node/src/AuthTokenProvider.ts
- packages/modules/msal-node/src/create-auth-cache.ts
- packages/modules/msal-node/src/create-auth-client.ts
- packages/modules/msal-node/src/create-auth-server.ts
- packages/modules/msal-node/src/enable-module.ts
- packages/modules/msal-node/src/error.ts
- packages/modules/msal-node/src/index.ts
- packages/modules/msal-node/src/module.ts
- packages/modules/msal-node/tsconfig.json
- pnpm-lock.yaml
- Implemented the core authentication module using MSAL for Node.js.
- Added support for multiple authentication modes: token-only, interactive, and silent.
- Created interfaces and classes for authentication configuration and providers.
- Introduced a persistence cache for secure token storage.
- Developed utility functions for creating authentication clients and servers.
- Included error handling for various authentication scenarios.
- Provided example usage in the module documentation.
closes:
> feat(msal-node): add MSAL Node module for Azure AD authentication

- .changeset/twenty-beers-study.md
- packages/react/app/src/help-center/useHelpCenter.ts
Ref [AB#62071](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/62071)
closes:
> fix(react-app): add comments to the `useHelpCenter` hook

- .github/workflows/actions/node-setup/action.yml
> chore(workflows): add `--frozen-lockfile` to `pnpm install`

- biome.json
- cookbooks/app-react-bookmark-advanced/src/Create.tsx
- cookbooks/app-react-bookmark-advanced/src/Page1.tsx
- cookbooks/app-react-bookmark-advanced/src/Page2.tsx
- cookbooks/app-react-bookmark/src/App.tsx
- packages/dev-portal/src/AppLoader.tsx
- packages/dev-portal/src/ContextSelector/ContextSelector.tsx
- packages/dev-portal/src/FusionLogo.tsx
- packages/dev-portal/src/Header.tsx
- packages/modules/context/src/ContextProvider.ts
- packages/react/components/bookmark/src/components/create-bookmark/CreateBookmark.tsx
- packages/react/components/bookmark/src/components/edit-bookmark/EditBookmark.tsx
- packages/react/legacy-interopt/src/LegacyAppContainer.ts
- packages/utils/observable/src/react/useObservableRef.ts
Removes overridden linting rules from `biome.json` to use Biome's default configuration and best practices. This eliminates custom rule level overrides and lets Biome use its built-in defaults for stricter code quality.
- `complexity/noBannedTypes` (warn → error)
- `complexity/noCommaOperator` (warn → error) 
- `performance/noAccumulatingSpread` (warn → error)
- `suspicious/noConfusingVoidType` (info → error)
- `suspicious/noExplicitAny` (warn → error)
- `suspicious/noEmptyBlockStatements` (warn → error)
- `suspicious/noGlobalIsNan` (warn → error)
- `suspicious/noDoubleEquals` (warn → error)
- `suspicious/noAssignInExpressions` (warn → error)
- `suspicious/noImplicitAnyLet` (warn → error)
- Fixed `noAssignInExpressions` violations in 4 files by converting assignment expressions to proper …
> chore: remove Biome rule overrides to use default best practices

- packages/modules/telemetry/src/TelemetryProvider.interface.ts
- packages/modules/telemetry/src/adapters/console/adapter.ts
- packages/modules/telemetry/src/static.ts
- Enhanced TelemetryProvider interface with comprehensive TSDoc documentation
- Added detailed usage examples for all tracking methods  
- Improved console adapter with color-coded titles based on telemetry levels
- Enhanced metric formatting with human-readable time display
- Refined telemetry enum documentation for better developer experience
No - these are enhancements that improve developer experience without changing APIs
These improvements enhance the developer experience when working with the telemetry module, providing better documentation and more readable console output for debugging.
ref: #3483
- _My PR is not a duplicate, [check existing …
> feat(telemetry): enhance interface documentation and console adapter UX

- packages/modules/module/src/configurator.ts
This PR introduces a bug fix for module initialization streams.
Currently, module initialization streams may not complete properly when no modules are present, potentially causing hanging or incomplete initialization.
Module initialization streams now properly complete even when empty by adding `defaultIfEmpty` operators to ensure stream completion.
No, this is a non-breaking bug fix.
This is a patch for #3490.
> fix: handle empty module initialization streams

- .changeset/fusion-query_event-system.md
- .github/workflows/pr.yml
- packages/utils/query/README.md
- packages/utils/query/package.json
- packages/utils/query/src/Query.ts
- packages/utils/query/src/QueryTask.ts
- packages/utils/query/src/cache/QueryCache.ts
- packages/utils/query/src/cache/events.ts
- packages/utils/query/src/cache/index.ts
- packages/utils/query/src/client/QueryClient.ts
- packages/utils/query/src/client/actions.ts
- packages/utils/query/src/client/events.ts
- packages/utils/query/src/client/index.ts
- packages/utils/query/src/client/reducer.ts
- packages/utils/query/src/events.ts
- packages/utils/query/src/index.ts
- **What kind of change does this PR introduce?** Feature - Adds a comprehensive event system for observability and telemetry integration
- **What is the current behavior?** The Fusion Framework query system relies on console logging which floods logs and makes debugging difficult. No structured way to monitor query lifecycle, cache operations, or client execution stages.
- **What is the new behavior?** A complete event system that emits structured events for all query operations, enabling proper telemetry logging, debugging, and performance monitoring without console spam.
- **Does this PR introduce a breaking change?** No - All changes are backwards compatible. Existing APIs remain unchanged.
- **Other information?** This implements the core telemetry functionality needed for Fusion …
> feat(fusion-query): add comprehensive event system for telemetry
