- packages/react-app/README.md
- packages/react-app/package.json
- packages/react-app/src/create-app.tsx
- packages/react-app/src/http/useHttpClient.ts
- packages/react-app/src/index.ts
- packages/react-app/src/modules.tsx
- packages/react-app/tsconfig.json
- yarn.lock
+ use module creator in create-app
+ retype module interfaces
+ update hooks for accessing module context
+ update `useHttpClients` to re-use module hook
+ update docs
> feat(react-app): implement react framework modules

- packages/framework-react/src/hooks/use-framework.ts
To be able to access your own modules using the useFramework hook on need to write the code below.
```TS
type MyModule = { name: 'myModule'; initialize: () => { test: 'test' } };
const useSometing = () => {
const  { modules }  = useFramework() as Fusion<[MyModule]>
return modules .myModule
}
```
I would prefer to write 
```TS
type MyModule = { name: 'myModule'; initialize: () => { test: 'test' } };
export const useMyModule = () => {
const { modules } = useFramework<[MyModule ]>();
return modules.myModule;
};
```
> chore(framework-react): update types for useFramework

- packages/observable/package.json
- packages/observable/src/ReactiveObservable.ts
- packages/observable/src/__tests__/Query.test.ts
- packages/observable/src/query/Query.ts
- packages/observable/src/query/cache/QueryCache.ts
- packages/observable/src/query/cache/actions.ts
- packages/observable/src/query/cache/create-reducer.ts
- packages/observable/src/query/cache/types.ts
- packages/observable/src/query/client/QueryClient.ts
- packages/observable/src/types.ts
+ support trimming of cache
+ add timestamp for last updated
+ allow providing `transaction` on requests
+ allow providing `QueryCache` when creating `Query`
+ allow providing `QueryClient` when creating `Query`
+ Observe `QueryClient` in `Query` and update `QueryCache`
+ update logic behind `Query.query`
+ `Query.queryAsync` has parameter for first or last emitted value
- remove feature for `refresh` on `QueryCache`
- remove `QueryClient` subscription on `success` for `QueryCache`
- remove `ref` from `QueryCacheRecord`, use `transaction`
TODO: fix tests in future
> feat(observable): enhance cache system

- packages/module-app/src/provider.ts
- packages/module-context/src/client/ContextClient.ts
- packages/module-context/src/configurator.ts
- packages/module-service-discovery/package.json
- packages/module-service-discovery/src/client.ts
- packages/module-service-discovery/tsconfig.json
- packages/observable/src/ReactiveObservable.ts
- packages/observable/src/query/Query.ts
- packages/observable/src/query/cache/actions.ts
- packages/observable/src/query/cache/types.ts
- packages/observable/src/query/client/QueryClient.ts
- packages/observable/src/query/client/actions.ts
- packages/observable/src/query/client/epics.ts
- packages/observable/src/query/client/index.ts
- packages/observable/src/query/client/operators.ts
- packages/observable/src/query/client/reducer.ts
- packages/observable/src/query/client/types.ts
- packages/observable/src/query/index.ts
- packages/observable/src/query/operators.ts
- packages/observable/src/query/types.ts
- packages/observable/src/react/index.ts
- packages/observable/src/react/useDebounceQuery.ts
- packages/test-app/package.json
- packages/test-app/src/pages/context/GetContext.tsx
- packages/test-app/src/pages/context/QueryContext.tsx
previously the client could only execute one query, now i has an internal queue of task, which the query connects to, this is to handle if multiple sources ask for same resource which are not within same scope.
> Feat(observable): handle queue operator

- packages/react-app/package.json
Fixing optional dependencies resolve error for ``fusion-framwork-react-app``.
Dependency ``fusion-framework-react-module-context`` to version 1.0.1
> fix(react-app): fix optional dependencie version react-module-context

- packages/module-http/src/lib/client/types.ts
Adding 2 missing types on IHttpClient interface on module-http
> fix(module-http): adding missing types on module-http iHttpClient

- packages/app/src/configure-modules.ts
- packages/react-app/src/create-legacy-app.tsx
- packages/react-app/tsconfig.json
since legacy `@equinor/fusion-cli` not yet has `@equinor/fusion-framework-module-app` configured, manifest is not provided during init of application modules
closes #497
> fix(react-app): check if manifest is provided in env

- packages/module-service-discovery/src/client.ts
- packages/module-service-discovery/src/provider.ts
allow to access environment from service discovery.
when trying to access this attribute without a loaded environment an error will been thrown.
this attribute is most likely only used internally (case the breaking change)
BREAKING CHANGE: changed `environment` from promise to sync
> feat(module-service-discovery): allow sync resolve of service

- packages/modules/signalr/src/SignalRModuleConfigurator.ts
- packages/modules/signalr/src/SignalRModuleProvider.ts
Remove AbortError form console log under development, and added log level to signal r config
> chore: remove signal r hub connection error in development

- packages/cli/src/scripts/app-config.ts
Converting the file path to an URL ensures this works on any environment (windows, linux, ...) 
Tested locally on windows and it works (without this change, it doesn't)
Should probably be tested more thoroughly.
> Fix path resolution in app-config.ts

- packages/modules/navigation/package.json
- packages/modules/navigation/src/provider.ts
- yarn.lock
when using the `createRouter` from the provider, the router does not prepend basename
https://github.com/remix-run/react-router/blame/852e05ae4132132cf5dd82ffff4c7e5be76672ae/packages/router/router.ts#L716
> fix(module-navigation): prepend basename

- packages/modules/context/src/ContextProvider.ts
- packages/modules/context/src/module.ts
when connecting to parent connect module, only skip first context item if there was no context resolved during initialize.
> fix(module-context): only skip first context item if not resolved

- .changeset/curvy-students-serve.md
- .changeset/quick-spiders-type.md
- .changeset/spicy-dolphins-call.md
- .changeset/violet-needles-join.md
- .eslintignore
- .gitignore
- packages/modules/module/src/index.ts
- packages/modules/module/src/lib/index.ts
- packages/modules/module/src/lib/provider/BaseModuleProvider.ts
- packages/modules/navigation/package.json
- packages/modules/navigation/src/index.ts
- packages/modules/navigation/src/lib/index.ts
- packages/modules/navigation/src/lib/provider/INavigationProvider.ts
- packages/modules/navigation/src/lib/provider/NavigationProvider.ts
- packages/modules/navigation/src/lib/provider/index.ts
- packages/modules/navigation/src/module.ts
Align `NavigationProvider` with `BaseModuleProvider`
closes:
> update navigation provider provider

- .changeset/clean-bats-heal.md
- .github/labeler.yml
add label when GitHub Pages documentation updates
closes:
> chore: update auto labeling

- .changeset/ninety-lizards-sin.md
- packages/cli/src/scripts/app-config.ts
This will fix so that both `"main": "src/index.ts"` and `"main": "/src/index.ts"` will resolve.
Closes #908
closes:
> fix(cli): remove requirement of leading slash in main attr

- .changeset/rotten-walls-reflect.md
- packages/modules/module/src/BaseConfigBuilder.ts
We add config builder callbacks so that configurator can process config with the builder callback args - for instance !requireInstance`
closes:
> fix(module): add config builder callback args to process config method

- .changeset/fluffy-turtles-live.md
- packages/react/legacy-interopt/src/create-legacy-render.tsx
BREAKING CHANGE: args for `createLegacyRender` has changed, legacy app manifest required!
mutation of manifest is no longer pushed to framework, only to legacy fusion context container.
`createLegacyRender` depended on `manifest.context` for emulating the context module (which is not there 🤯)
closes:
> fix(react-legacy-interopt): fix legacy render

- .changeset/flat-paws-glow.md
- .gitignore
- package.json
- packages/modules/navigation/package.json
- packages/modules/navigation/src/module.ts
- yarn.lock
use `genversion` on all packages on post install from root package.json
when executing `yarn` a `src/version.ts` will be generated in all packages
closes:
> fix: update generate version for packages

- .changeset/eight-poems-mate.md
- packages/react/components/bookmark/package.json
- packages/react/components/bookmark/src/components/BookmarkProvider.tsx
- packages/react/components/bookmark/src/components/create-bookmark/CreateBookmark.tsx
- packages/react/components/bookmark/src/components/edit-bookmark/EditBookmark.tsx
- packages/react/components/bookmark/src/components/sectionList/SectionList.tsx
- packages/react/components/bookmark/tsconfig.json
build fails since `@equinor/fusion-framework-react-components-bookmark` depends on other framework modules to compile
closes:
> build: fix missing references

- .changeset/gorgeous-buckets-draw.md
- packages/react/app/src/context/index.ts
- packages/react/app/src/context/useContextProvider.ts
- packages/react/app/src/context/useCurrentContext.ts
convenience hook for `useAppModule('context')`
created for @thomasFjorstad 
closes:
> create hook which return ContextProvider for scoped app 

- vue-press/src/.vuepress/config.ts
The current font URL in the vite config is outdated. The correct one is now: 
https://cdn.eds.equinor.com/font/equinor-font.css
closes:
~https://github.com/equinor/fusion-framework/issues/980~
EDIT: As pointed out by @eikeland, this only updates the vuepress documentation site. I'll let it stand as I guess that's useful as well :)
> fix: corrected the font URL

- .changeset/twelve-buttons-double.md
- packages/cli/package.json
- yarn.lock
Updating fusion-framework-cli dependency @equinor/fusion-react-styles to 0.5.6
To use the correct cdn link to the Equinor font.
Closes #980 
> fusion-framework-cli: updating  fusion-react-styles to 0.5.6

- .changeset/forty-cherries-destroy.md
- packages/react/legacy-interopt/src/LegacyAppContainer.ts
The LegacyAppContainer's implementation of FeatureLogger was not logging the current appKey.
Changing `currentManifest.key` to `current.appKey` fixed the issue.
Closes #1016
> Fix/legacy interopt/feature logger

- .changeset/famous-sheep-peel.md
- packages/react/modules/event/src/EventProvider.tsx
- packages/react/modules/event/src/eventContext.ts
- packages/react/modules/event/src/index.ts
- packages/react/modules/event/src/useEventHandler.ts
- packages/react/modules/event/src/useEventProvider.ts
- packages/react/modules/event/src/useModulesEventProvider.ts
- vue-press/src/modules/event/README.md
Add functionality for controlling which event provider which is used within the event hooks 
closes:
> Feat(react-module-event): add event provider

- .changeset/long-walls-vanish.md
- packages/app/src/AppConfigurator.ts
- What kind of change does this PR introduce? 
- allow configuration of service discovery http client config
- What is the current behavior?
- when using configuration from service discovery, there are no option for altering the configuration
- What is the new behavior?
- allow providing `HttpClientOptions` when using `AppConfigurator.useFrameworkServiceClient`
- passes option to `AppConfigurator.configureClient` _(exludes baseUri and defaultScopes)_ 
- Does this PR introduce a breaking change?
- none 
```ts
type useFrameworkServiceClient = (
service_name: string,
/** new, allows customize registration of http client from service discovery */
options?: Omit<HttpClientOptions<any>, 'baseUri' | 'defaultScopes'>,
)
```
closes:
- _My code does not generate …
> feat(app): allow configuration of service discovery http client

- .github/workflows/cache-cleanup.yml
- .github/workflows/cache-prime.yml
- .github/workflows/release.yml
> chore: add clean-up workflow

- .changeset/tough-plums-speak.md
- packages/modules/http/src/lib/client/client.ts
- append `Accept: application/json` to request when using client json calls
closes:
> fix(module-http): add accept headers to http client

- .changeset/unlucky-kiwis-change.md
- packages/utils/query/src/cache/create-reducer.ts
__What kind of change does this PR introduce?__
Correctly return the cache hit on first access
__What is the current behavior?__
Since `updated` is not set until an actual update, all initial cache hits will miss (first hit)
__What is the new behavior?__
The query client cache will now set `updated` to `created` date when initially created 
__Other information?__
apps and portals using this package should update, rebuild and redeploy to improve network calls. 
> fix(query): fix first cache hit

- .changeset/lazy-flowers-pull.md
- packages/modules/http/src/lib/client/client.ts
- packages/modules/http/src/lib/client/types.ts
- packages/modules/http/src/lib/selectors/blob-selector.ts
- packages/modules/http/src/lib/selectors/index.ts
add method for executing blob requests
- add selector for extracting blob from response
- add function for fetching blob as stream or promise on the http client
closes:
> feat(module-http): add functionality for blob query

- .changeset/spicy-bottles-tease.md
- packages/modules/services/src/people/api-models.ts
- packages/modules/services/src/people/client.ts
- packages/modules/services/src/people/person-details/client.ts
- packages/modules/services/src/people/person-details/generate-endpoint.ts
- packages/modules/services/src/people/person-details/generate-parameters.ts
- packages/modules/services/src/people/person-details/index.ts
- packages/modules/services/src/people/person-details/types.ts
- packages/modules/services/src/people/person-photo/client.ts
- packages/modules/services/src/people/person-photo/generate-endpoint.ts
- packages/modules/services/src/people/person-photo/generate-parameters.ts
- packages/modules/services/src/people/person-photo/index.ts
- packages/modules/services/src/people/person-photo/types.ts
- packages/modules/services/src/people/query/client.ts
- packages/modules/services/src/people/query/generate-endpoint.ts
- packages/modules/services/src/people/query/generate-parameters.ts
- packages/modules/services/src/people/query/index.ts
- packages/modules/services/src/people/query/types.ts
- packages/modules/services/src/people/static.ts
- packages/modules/services/src/provider.ts
- packages/modules/services/src/types.ts
initial people service
initial api implementations of people service
> this module is meant for internal usage
lacking documentation, but not meant for consumption outside 'core' functionality
closes:
> feat(module-services): add people api

- .changeset/four-swans-sip.md
- packages/react/components/people-resolver/README.md
- packages/react/components/people-resolver/package.json
- packages/react/components/people-resolver/src/PeopleResolver.tsx
- packages/react/components/people-resolver/src/PeopleResolverProvider.tsx
- packages/react/components/people-resolver/src/PersonController.ts
- packages/react/components/people-resolver/src/create-resolver.ts
- packages/react/components/people-resolver/src/index.ts
- packages/react/components/people-resolver/src/makeResolver.tsx
- packages/react/components/people-resolver/src/types.ts
- packages/react/components/people-resolver/tsconfig.json
- pnpm-lock.yaml
Component for providing people api resources to the @equinor/fusion-wc-person and @equinor/fusion-react-person components
mapping and caching of `@equinor/fusion-framework-module-services/people`
> Strongly collated to the Fusion ecosystems
```tsx
import { PeopleResolverProvider } from '@equinor/fusion-framework-react-components-people-provider';
<PeopleResolverProvider>
<fwc-person-avatar azureId='cbc6480d-12c1-467e-b0b8-cfbb22612daa'></fwc-person-avatar>
<fwc-person-card azureId='cbc6480d-12c1-467e-b0b8-cfbb22612daa'></fwc-person-card>
<fwc-person-list-item azureId='cbc6480d-12c1-467e-b0b8-cfbb22612daa'></fwc-person-list-item>
</PeopleResolverProvider>
```
- _My PR is not a duplicate, [check existing …
> Feat/react/components/people resolver/initial

- .changeset/breezy-zoos-marry.md
- .github/workflows/pr.yml
- packages/modules/services/package.json
- packages/modules/services/src/people/api-models.v4.ts
- packages/modules/services/src/people/person-details/types.ts
- packages/modules/services/src/people/utils.ts
add util for checking if object is person
> extremely crude, but good enough until backend comes of with new models or endpoint
_updated typings for person v4_
closes:
> feat(module-services): add compare util

- .changeset/metal-tools-type.md
- .changeset/tame-wolves-heal.md
- packages/modules/app/src/app/flows.ts
- packages/utils/query/src/Query.ts
- packages/utils/query/tests/Query.test.ts
> Fix(utils/query): execute query on observe

- .changeset/afraid-bulldogs-serve.md
- .changeset/five-days-sort.md
- packages/cli/src/bin/dev-portal/main.tsx
- packages/cli/src/bin/dev-portal/resources/fallback-photo.svg.ts
- packages/react/components/people-resolver/README.md
- packages/react/components/people-resolver/src/PeopleResolverProvider.tsx
- packages/react/components/people-resolver/src/PersonController.ts
- packages/react/components/people-resolver/src/create-resolver.ts
- packages/react/components/people-resolver/src/makeResolver.tsx
Allow `PeopleResolverProvider` to support fallback image when api controller fails to resolve photo
> feat(react-component-people-resolver): allow fallback photo

- .changeset/happy-moose-wave.md
- cookbooks/app-react-ag-grid/package.json
- cookbooks/app-react-ag-grid/src/App.tsx
- pnpm-lock.yaml
> build(app-react-cookbook): update ag-grid@30.2

- .changeset/spicy-bags-develop.md
- packages/cli/src/bin/create-dev-serve.ts
- packages/cli/src/bin/dev-proxy.ts
- packages/cli/src/bin/main.app.ts
This PR adds a new flag to the fusion-framework-cli (`--dev-portal`), which is meant to pass in a path to a custom portal-bundle, which decouples the fusion framework a bit more from fusion.equinor.com itself. This is done to allow more flexibility for consumers of the fusion-framework who are not necessarily building apps for the fusion portal.
In addition, I have added proxying for /api/apps (previously only /api/apps/:id was handled).
There should be no breaking changes introduced by this PR, as the flag would need to be set for it to have any effect. 
> feat(cli): Add --dev-portal flag to facilitate using a custom portal

- .changeset/lovely-impalas-help.md
- packages/modules/navigation/src/navigator.ts
missing fall-threw on navigator slave
closes:
> fix(navigation): double navigation

- .changeset/cool-countries-doubt.md
- packages/modules/navigation/src/configurator.ts
- packages/modules/navigation/src/module.ts
- packages/modules/navigation/src/navigator.ts
check previous state before dispatching push and replace.
partially rolls back #1453 since no longer needs `master` & `slave`
closes:
> fix(module-navigation): check previous state

- .changeset/small-buckets-draw.md
- packages/cli/src/bin/create-dev-serve.ts
> fix(cli): use provided config path when developing

- .changeset/five-frogs-cheer.md
- packages/cli/src/bin/bundle-application.ts
- packages/cli/src/bin/main.app.ts
Allow providing archive name when bundling application
closes:
fixes [AB#45894](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/45894)
> feat(cli): allow setting archive name

- packages/modules/bookmark/src/client/bookmarkClient.ts
After creating a bookmark the bookmark module will no longer set it as current. This makes sense because the application is already in the correct state when the bookmark was created
closes: #1547 
My PR doesnt build because the ./version file is missing. Is this a known issue?
https://github.com/equinor/fusion-framework/blob/main/packages/modules/navigation/src/module.ts#L13
> fix: :bug: #1547

- .changeset/cool-forks-type.md
- packages/modules/http/src/errors.ts
- packages/modules/http/src/lib/selectors/json-selector.ts
- added `HttpJsonResponseError` which extends `HttpResponseError`
- updated `jsonSelector` to throw `HttpJsonResponseError` on failure
> fix(http): Refactor HTTP error handling and JSON parsing

- .changeset/neat-schools-kiss.md
- packages/react/modules/http/package.json
Fixes package exports in react-module-http.
When using the package with `moduleResolution: bundler` you run into the following issue.
```
There are types at 'c:/Users/gustav.eikaas/repo/cc-components/node_modules/@equinor/fusion-framework-react-module-http/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@equinor/fusion-framework-react-module-http' library may need to update its package.json or typings.
```
> fix: package exports react-module-http

- .changeset/happy-radios-return.md
- packages/react/components/bookmark/src/components/Bookmark.tsx
- packages/react/components/bookmark/src/components/messages/Message.tsx
- packages/react/components/bookmark/src/components/sectionList/SectionList.tsx
closes:
Implement a "No Content" message and relocate the "Loading" indicator to the bookmarks component. Additionally, incorporate an effect to handle cases where the "onBookmarksChanged" event is not triggered.
> feat(bookmarks): no content message

- .changeset/popular-beers-fry.md
- packages/modules/http/package.json
Vite gives an error message when using moduleResolution: bundler. The reason is that the package fusion-framework-react-module-http package attempts to import 👇. But the `/errors` export is not specified in package.json
```TS
// @equinor/fusion-framework-react-module-http index.js
export { HttpResponseError, HttpJsonResponseError, } from '@equinor/fusion-framework-module-http/errors';
```
I manually added the export declaration in node_modules and my project ran smoothly afterwards
> fix: moduleresolution bundler [@equinor/fusion-framework-module-http]

- .changeset/nice-chairs-remember.md
- packages/modules/feature-flag/src/FeatureFlagConfigurator.ts
- Added imports for createApiPlugin and createCgiPlugin from the ./plugins module.
- Updated the IFeatureFlagConfigurator interface with new method signatures.
- The addPlugin method now has a JSDoc comment describing its usage.
- The enableCgi method now has a JSDoc comment and parameter description.
- The enableApi method now has a JSDoc comment and parameter description.
- Modified the FeatureFlagConfigurator class:
- Added implemented interface IFeatureFlagConfigurator.
- Added a private property #plugins as an array of FeatureFlagPluginConfigCallback.
- Updated the addPlugin method to append the new plugin handler to the #plugins array.
- Added the enableCgi method, which calls createCgiPlugin with the passed arguments and adds the result to the #plugins array.
- Added the enableApi …
> Feat/feature flagging/simplify configurator

- .changeset/sixty-spies-flow.md
- packages/modules/bookmark/src/client/bookmarkClient.ts
- packages/modules/bookmark/src/client/bookmarkFlows.ts
- packages/modules/bookmark/src/configurator.ts
- packages/modules/bookmark/src/types.ts
fixing the infinite loading if a bookmark is created in classic fusion.
closes: 
The `sourceSystem` form fusion classic is undefined this results in a filter function failing and not returning any bookmarks resulting in a infinite spinner. This simple fix will fix it and return other bookmarks.
> fix(bookmark-module): fixing the infinite loading 

- .changeset/small-apples-grow.md
- packages/cli/package.json
- pnpm-lock.yaml
bumping fwc-person to get latest fixes from web-component.
Reference [AB#48075](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/48075)
> fix(cli): bumping fwc-person to get latest fixes from web-component

- .changeset/hip-wasps-brake.md
- cookbooks/app-react-feature-flag/package.json
- packages/cli/package.json
- packages/react/components/bookmark/package.json
- pnpm-lock.yaml
The latest eds-icons have a type conflict and requires the latest eds-core-react along side it.
This pr is just to skip the dependabot update that updates a single dep at the time.
> Updated all eds packages to mitigate type issues with eds-icons

- .changeset/green-chicken-rush.md
- packages/utils/observable/src/create-action.ts
> fix(utils-observable): fix action suffix matcher

- .changeset/few-dragons-do.md
- packages/modules/app/src/AppModuleProvider.ts
improve type of current application
- result will be `undefined` if current application has never been set
- result will be `IApplication` if current application is set
- result will be `null` if current application is cleared
closes:
> fix(module-app): improve type of current application

- .changeset/breezy-points-beg.md
- packages/utils/observable/src/react/useObservableState.ts
hook return `undefined` as value in the first `tick` _(useLayoutEffect)_ 
> improve handling of initial value when using `useObservableState`

- .changeset/quick-items-provide.md
- packages/react/framework/src/app/useCurrentApp.ts
- packages/react/framework/src/app/useCurrentAppModule.ts
- packages/react/framework/src/app/useCurrentAppModules.ts
improve handling of possible null and undefined
> refactor(react-framework): update possible null and undefined

- .changeset/chilled-bugs-judge.md
- packages/react/components/people-resolver/src/PeopleResolverProvider.tsx
- Removed todo from the PeopleResolve
- Add fallback to PeopleResolveProviderProps
closes:
> chore(PeopleResolver): remove todo 

- .changeset/wicked-plants-joke.md
- packages/cli/src/lib/app-manifest.ts
missing legacy `resources` in defineAppManifest
see [issue 286](https://github.com/equinor/fusion/issues/286#issuecomment-1923401234)
> fix(cli): allow providing resources in defineAppManifest

- .changeset/hungry-needles-drop.md
- packages/react/legacy-interopt/src/LegacyAppContainer.ts
Some users on IE would get stuck in loading since `setCurrentAppAsync` await injection of script _(which might previously been loaded)_
> [!CAUTION]
> the host (portal) need to load the application script
closes:
BREAKING CHANGE: `setCurrentAppAsync` no longer injects script for loading application
> fix(legacy-interopt): remove script injection

- .changeset/small-experts-watch.md
- packages/modules/module/src/BaseConfigBuilder.ts
- packages/modules/module/src/utils/dot-path.ts
improve resolve of dot path objects
> we might need to deprecate dot in future since TS does not really support recursive type resolve 
closes:
> fix(module): improve-object-path-resolve

- contributing/reviewing.md
Ads reviewing guidelines
closes:
> docs: add reviewing guidelines

- .changeset/dirty-buses-kneel.md
- cookbooks/app-react-ag-grid/package.json
- packages/modules/ag-grid/package.json
- pnpm-lock.yaml
bump ag-grid from 31.0.3 to 31.1.1
closes: #1883
> chore: update ag-grid dependencies to version 31.1.1

- .changeset/tidy-socks-clean.md
- packages/react/app/package.json
Update type exports in `fusion-framework-react-app` package.json
Closes #1954 
> fix(app-react): change types exports in package

- .changeset/tall-apples-build.md
- package.json
- packages/app/package.json
- packages/cli/package.json
- packages/framework/package.json
- packages/modules/event/package.json
- packages/modules/services/package.json
- packages/react/app/package.json
- packages/react/components/bookmark/package.json
- packages/react/components/people-resolver/package.json
- packages/react/framework/package.json
- packages/react/modules/event/package.json
- packages/react/modules/module/package.json
- packages/react/modules/signalr/package.json
- packages/react/widget/package.json
- packages/widget/package.json
Not all packages had correct exports defined according to node(10+) documentation.
This should make sure we support developers setting tsconfig moduleResolution to both node and node(16|Next).
Reference #1968 
> fix(exports): make sure all packages have proper export syntax

- .changeset/breezy-scissors-speak.md
- .changeset/loud-waves-laugh.md
- packages/modules/http/package.json
- packages/modules/http/src/lib/client/client.ts
- packages/modules/http/src/lib/operators/process-operators.ts
- packages/modules/http/src/lib/operators/types.ts
- packages/modules/http/tests/HttpClient.test.ts
- packages/modules/http/tsconfig.json
- packages/modules/http/vitest.config.ts
- pnpm-lock.yaml
> Fix(module-http): prevent modification to config

- .changeset/twenty-boxes-wait.md
- packages/utils/query/src/cache/QueryCache.ts
- packages/utils/query/src/cache/actions.ts
- packages/utils/query/src/cache/create-reducer.ts
> feat(query): allow invalidating of all cache

- .changeset/tricky-carpets-rush.md
- packages/cli/src/lib/vite-config.ts
- packages/cli/vite.config.ts
- packages/utils/query/README.md
- packages/utils/query/src/logger.ts
missing process env in production building of applications
closes: https://github.com/equinor/fusion/issues/343
> fix: update FUSION_LOG_LEVEL configuration in vite config generation

- package.json
set required pnpm version to 9.
> fix(pnpm): setting required pnpm to v9

- .changeset/allow-async-config-builder-overrides.md
- .changeset/improve-docs-baseconfig-builder.md
- .changeset/improve-extendability-config-builder.md
- packages/modules/module/src/BaseConfigBuilder.ts
This PR introduces changes to the `BaseConfigBuilder` class in the `@equinor/fusion-framework` package. The current behavior of the `BaseConfigBuilder` class is that it provides a way to build and configure modules by defining configuration callbacks for different parts of the module's configuration. However, the implementation has some limitations and lacks proper documentation.
The new behavior introduced by this PR is an improved and more flexible implementation of the `BaseConfigBuilder` class. It includes better handling of nested configurations, improved type safety, and more comprehensive documentation. Additionally, it introduces new helper methods for working with configuration callbacks and adds examples to illustrate the usage of the class.
This PR does not introduce any …
> Feat(base config builder): allow async overrides

- .changeset/event-improve-type-resolve.md
- packages/modules/event/src/event.ts
- packages/modules/event/src/index.ts
This PR introduces changes to the `FrameworkEventInitType` utility type in the `@equinor/fusion-framework` package. The current behavior is that the `FrameworkEventInitType` type only handles events that extend the `IFrameworkEvent` interface. The new behavior is that it also handles events that extend the `FrameworkEvent` class.
This change does not introduce a breaking change, as it only extends the functionality of the existing `FrameworkEventInitType` type.
closes: N/A (no issue referenced)
> feat(event): enhance FrameworkEventInitType type definition

- .changeset/fifty-pianos-reflect.md
- packages/modules/http/src/lib/selectors/json-selector.ts
This pull request introduces a fix to the `jsonSelector` function in the `@equinor/fusion-framework-module-http` package.
The current behavior is that the `jsonSelector` function was not properly checking the error type in the `catch` block. This led to always throwing a parser error, even when the correct error was in the `cause` property of the `HttpJsonResponseError`.
The new behavior is that the `jsonSelector` function now correctly checks if the error is an instance of `HttpJsonResponseError`, and then properly handles the error data and cause. This ensures that developers who have caught the error and assumed the `cause` property would give the proper error data, will now receive the correct information.
**This change might introduce breaking changes:**
If for some reason developers …
> fix(http)!: throw correct error in jsonSelector

- .changeset/smooth-chefs-happen.md
- vue-press/src/guide/app/getting-started.md
Removed the warning block that stated the Fusion Portal only supports React 17, as this information is no longer relevant or accurate in the current state of the project. This change helps simplify the getting started guide and avoids confusion for users.
ref: https://github.com/equinor/fusion/issues/346
> docs: remove React version warning from getting started guide

- .changeset/old-nails-confess.md
- pnpm-lock.yaml
- vue-press/package.json
Update the following dependencies in vue-press/package.json:
- Bump @vuepress/bundler-vite from 2.0.0-rc.9 to 2.0.0-rc.11
- Bump @vuepress/cli from 2.0.0-rc.9 to 2.0.0-rc.11
- Bump @vuepress/client from 2.0.0-rc.9 to 2.0.0-rc.11
- Bump @vuepress/plugin-register-components from 2.0.0-rc.21 to 2.0.0-rc.30
- Bump @vuepress/utils from 2.0.0-rc.9 to 2.0.0-rc.11
- Bump mermaid from ^10.9.0 to ^10.9.1
- Bump vuepress from 2.0.0-rc.9 to 2.0.0-rc.11
- Bump vuepress-theme-hope from 2.0.0-rc.37 to 2.0.0-rc.43
> Chore(deps): update vue press

- .changeset/three-snakes-peel.md
- packages/utils/observable/package.json
- pnpm-lock.yaml
> feat(observable): upgrade @testing-library/react to v15.0.7

- .changeset/purple-mice-know.md
- .changeset/quiet-donuts-beg.md
- cookbooks/app-react-ag-grid/package.json
- packages/modules/ag-grid/package.json
- pnpm-lock.yaml
This pull request updates the `@ag-grid-enterprise/core` dependency to version `~31.3.2` in the `@equinor/fusion-framework-module-ag-grid` package.
> Chore(ag grid): update to version 31.3

- .changeset/cool-vans-worry.md
- packages/modules/module/src/BaseConfigBuilder.ts
`ConfigBuilderCallback` in `BaseConfigBuilder` has now type-guard for only accepting `ObservableInput` as the return type.
The method never supported synchronous return types, but the type-guard was missing.
> refactor(module): Update ConfigBuilderCallback to use ObservableInput

- .changeset/popular-mangos-rescue.md
- packages/modules/event/package.json
- packages/modules/event/src/event.ts
- pnpm-lock.yaml
Add a feature enabling event listeners to mutate event details, controlled by a new `allowMutate` flag in the event creation process. This enhancement leverages `immer` for immutability, ensuring that original event details remain unaffected by mutations in listeners.
> feat(module-event): allow event detail mutation

- .changeset/fluffy-olives-shout.md
- .changeset/sweet-bottles-bow.md
- packages/utils/query/src/Query.ts
- packages/utils/query/src/cache/QueryCache.ts
- packages/utils/query/tests/Query.mutations.test.ts
This PR introduces enhancements to the `Query` class in the `@equinor/fusion-query` package. It adds a new public method `generateCacheKey` and enhances the `mutate` method with more flexible cache mutation options.
- Added `generateCacheKey` method for advanced caching scenarios and debugging
- Enhanced `mutate` method with an optional `options` parameter
- Introduced `allowCreation` option for more flexible cache management
- Updated internal `QueryCache` class to support new features
> feat(fusion-query): Enhance mutate functionality

- .changeset/forty-trees-flow.md
- packages/modules/event/src/event.ts
The code changes add a try-catch block around the creation of immutable copies of event details in order to handle potential errors and disable mutations if the event details cannot be securely mutated. Additionally, the changes import and invoke `enableMapSet` from `immer` to support Map and Set types in Immer drafts.
Modified:
- Removed the initial assignment of `#detail` and `#originalDetail` to the immutable copy produced by `immer`. Instead, they are initially assigned the raw `args.detail` value.
- The assignment of `#detail` and `#originalDetail` to an immutable copy is now done inside the try block, ensuring that mutations are only disabled upon failure to create an immutable copy.
- The assignment of `#source` is now done directly from `args.source` without attempting to create …
> feat: Add try-catch block for creating immutable copies of event details

- .changeset/real-pigs-destroy.md
- packages/utils/observable/src/FlowSubject.ts
Adds new constructor overloads to the FlowSubject class, allowing for more flexible initialization with either a ReducerWithInitialState<S, A> or a Reducer<S, A> along with an initialState. It also introduces a new select method, which enables users to select and emit derived states from the FlowSubject's state based on custom logic. These changes enhance state management and selection capabilities in the FlowSubject class.
> feat: Add new select method to FlowSubject

- .changeset/empty-ants-remain.md
- packages/modules/module/src/BaseConfigBuilder.ts
This commit improves the handling of asynchronous configuration callbacks in the BaseConfigBuilder class. The BaseConfigBuilder._buildConfig method now correctly handles asynchronous configuration callbacks by removing the 'async' keyword and directly using RxJS operators. This change simplifies the handling of asynchronous configuration callbacks and improves the overall code structure.
closes:
> feat(module): Improve handling of configuration callbacks

- .changeset/nine-knives-reply.md
- packages/utils/log/src/ConsoleLogger.ts
- packages/utils/log/tests/ConsoleLogger.test.ts
Browser console did not format correctly objects
closes:
> fix(utils/log): Remove formatting of log messages in ConsoleLogger

- .changeset/thirty-rats-exercise.md
- packages/react/framework/src/Framework.tsx
- packages/react/framework/src/create-framework-provider.tsx
This commit updates the Framework component and createFrameworkProvider function to be consistent with the updated configuration approach and support module instances from the parent context. The following changes were made:
- Added useModules hook to import modules from the parent context in the Framework component.
- Updated the createFrameworkProvider function to accept a ref parameter for module instances.
- Replaced the deprecated import of FusionConfigurator with FrameworkConfigurator.
closes:
> feat(react-framework): Support framework creation with ref

- .changeset/clean-fans-kick.md
- packages/modules/module/src/BaseConfigBuilder.ts
**@equinor/fusion-framework-module:**
Updated the `_buildConfig` method in `BaseConfigBuilder` to improve error handling and configuration merging.
- Enhanced `_buildConfig` to log errors when a configuration callback fails, providing more detailed error messages.
- Improved the merging process of configuration callbacks by filtering out undefined values and mapping them to target-value pairs.
- Updated the `_buildConfig` method to initialize the accumulator with the initial configuration or an empty object.
```ts
type MyConfig = {
foo?: number;
bar?: string;
}
const initial = {foo: 1, bar: 'baz'};
export class MyConfigurator extends BaseConfigBuilder<MyConfig> {
setFoo(cb: ConfigBuilderCallback<MyConfig['foo']>){
this._set('foo', cb);
}
setBar(cb: ConfigBuilderCallback<MyConfig['bar']>){ …
```
> fix(module): Allow `void` in config callbacks 

- .changeset/quiet-scissors-breathe.md
- packages/cli/src/bin/plugins/app-proxy.ts
This pull request introduces the `appProxyPlugin`, a Vite plugin designed to streamline the development process for Fusion apps by proxying API and bundle requests to the Fusion app backend.
The `appProxyPlugin` addresses several key challenges faced during the development of Fusion apps:
1. **Token Preservation**: Ensures authorization tokens are preserved and reused for subsequent requests, simplifying authentication during development.
2. **Proxy Configuration**: Sets up proxy rules for API and bundle requests, allowing developers to work with local and remote resources seamlessly.
3. **App Configuration and Manifest**: Serves the app configuration and manifest based on the app key and version, ensuring the correct assets and settings are used during development.
```typescript
const …
```
> feat(cli): create plugin for handling application api calls

- .changeset/hot-ears-fix.md
- packages/cli/src/bin/plugins/external-public.ts
This PR introduces a new plugin `externalPublicPlugin` for the `@equinor/fusion-framework-cli`.
Currently, Vite's `spa` mode does not serve the `index.html` file from the specified external public directory.
The new plugin `externalPublicPlugin` fixes this issue by:
- Enhancing the middleware to intercept requests and serve the `index.html` file from the specified external public directory.
- Transforming the HTML using Vite's `transformIndexHtml` method.
- Applying appropriate content headers and additional configured headers before sending the response.
No, this PR does not introduce a breaking change.
closes:
- _My PR is not a duplicate, [check existing …
> feat(cli): create plugin for serving index.html from external public directory

- .changeset/spotty-eels-care.md
- packages/modules/module/src/configurator.ts
module configurator would throw error if post configure handlers where empty
replaced `scan` with `reduce` in `configurator.initialize`, since reduce always will emit at least initial value, while scan only emits if source emits values.
fixed handlers for `configurator._postInitialize`
```diff
- await lastVelaueFrom(postInitialize$)
+ await new Promise((resolve, reject) => {
+   postInitialize$.subscribe({complete: () => resolve(true), error: reject });
+ });
```
`lastVelaueFrom(postInitialize$)`would fail since `postInitialize$` did not emit any values
> refactor(module): fixed issue where post handlers where empty

- .changeset/rotten-drinks-sneeze.md
- packages/modules/http/src/lib/client/client.ts
This PR adds a new feature to the `HttpClient` class in the `@equinor/fusion-framework-module-http` package. The `HttpClient._resolveUrl` method now supports resolving URLs with a base URL that contains a path.
Before this change, when using the `HttpClient` to fetch a relative path, the base URL was not taken into account. With this change, the `HttpClient` correctly resolves the URL by appending the relative path to the base URL.
before:
```typescript
const client = new HttpClient('https://example.com/test/me');
client.fetch('/api'); // https://example.com/api
```
now:
```typescript
const client = new HttpClient('https://example.com/test/me');
client.fetch('/api'); // https://example.com/test/me/api
```
closes:
- _My code does not generate new linting …
> feat(http): Add support for resolving URLs with a base URL that contains a path

- .changeset/plenty-horses-accept.md
- packages/cli/src/bin/dev-portal/config.ts
changed service discover url to match #2452
closes:
> fix(http): Update baseUri to use origin of URL

- .changeset/angry-cows-lay.md
- .changeset/funny-pumpkins-train.md
- .changeset/moody-parents-confess.md
- .changeset/nervous-clocks-rest.md
- .changeset/violet-phones-hang.md
- packages/cli/src/bin/dev-portal/config.ts
- packages/cli/src/bin/dev-proxy.ts
- packages/modules/service-discovery/README.md
- packages/modules/service-discovery/package.json
- packages/modules/service-discovery/src/api-schema.ts
- packages/modules/service-discovery/src/client.ts
- packages/modules/service-discovery/src/configurator.ts
- packages/modules/service-discovery/src/constants.ts
- packages/modules/service-discovery/src/index.ts
- packages/modules/service-discovery/src/module.ts
- packages/modules/service-discovery/src/provider.ts
- packages/modules/service-discovery/src/types.ts
- packages/modules/signalr/src/lib/utils/configure-from-framework.ts
- packages/react/legacy-interopt/src/create-service-resolver.ts
- packages/widget/src/WidgetConfigurator.ts
- pnpm-lock.yaml
The Service Discovery module has been totally revamped to provide a more flexible and robust solution for service discovery in the Fusion Framework.
The module now relies on the Fusion Service Discovery API to fetch services and their configurations, which allows for more dynamic and real-time service discovery.
The module now follows the "best practices" for configuration and usage, and it is now easier to configure and use the Service Discovery module in your applications. But this also means that the module has breaking changes that may require updates to existing implementations.
> [!NOTE]
> This module can still be configured to resolve custom services, as long as the client implements the `IServiceDiscoveryClient` interface.
**Documentation Updates**
-   The README file has been …
> feat(service-discovery): Align service discovery with API service

- packages/modules/module/src/logger.ts
> fix(logger): Update log level to use FUSION_LOG_LEVEL environment variable

- .changeset/pink-laws-cough.md
- cookbooks/app-react/app.config.ts
- cookbooks/app-react/app.manifest.config.ts
- packages/cli/src/bin/build-application.ts
- packages/cli/src/bin/bundle-application.ts
- packages/cli/src/bin/create-export-manifest.ts
- packages/cli/src/bin/main.app.ts
- packages/cli/src/bin/utils/load-app-config.ts
- packages/cli/src/bin/utils/load-manifest.ts
- packages/cli/src/bin/utils/spinner.ts
- packages/cli/src/lib/app-config.ts
- packages/cli/src/lib/app-manifest.ts
- packages/cli/src/lib/app-package.ts
- packages/cli/src/lib/utils/config.ts
- packages/cli/src/lib/vite-config.ts
- packages/modules/app/src/types.ts
** @equinor/fusion-framework-cli**
**Changes:**
Updated commands in CLI to reflect purpose of the command:
- renamed `config` to `build-config` to generate build config of an application.
- renamed `pack`to `build-pack` to bundle an application.
- added `build-manifest` command to generate build manifest of an application.
> [!WARNING]
> Config callback for `manifest` and `config` now allows `void` return type. 
> Return value from callback is now merged with default config instead of replacing it, this might be a breaking change for some applications.
> [!NOTE]
> This mean that `mergeAppConfig` and `mergeManifestConfig` functions are no longer needed and can be removed from the application.
- _My PR is …
> Refactor(app): Update AppBuildManifest and AppManifest types

- .changeset/tidy-countries-beg.md
- packages/cli/src/lib/app-config.ts
Make `app.config.ts` definition scopes optional by updating the `AppConfigFn` type to use `z.input<typeof ApiAppConfigSchema>`.
> fix(cli): app-config.ts scopes optional

- .changeset/tidy-countries-beg.md
- .changeset/wild-chairs-confess.md
- packages/cli/src/lib/app-config.ts
- vue-press/src/guide/app/getting-started.md
Updated `getting-started.md` documentation to:
- Correct JSON code block formatting.
- Update `app.config.ts` example to use `defineAppConfig` directly without `mergeAppConfigs`.
- Provide an example of configuring an HTTP client with endpoint details from environment configuration.
> docs(vue-press): updating getting started

- .changeset/calm-hounds-applaud.md
- packages/cli/src/bin/bundle-application.ts
- Removed individual file additions for package.json, LICENSE.md, and README.md.
- Added a loop to handle multiple files (package.json, LICENSE.md, README.md, CHANGELOG.md) in a more concise manner.
- Updated the spinner messages accordingly.
> feat(cli): adds CHANGELOG.md to app package

- .changeset/slow-dodos-tease.md
- packages/react/legacy-interopt/src/create-fusion-context.ts
- packages/react/legacy-interopt/src/create-service-resolver.ts
- `packages/react/legacy-interopt/src/create-fusion-context.ts`
- `packages/react/legacy-interopt/src/create-service-resolver.ts`
1. **create-fusion-context.ts**
- Added a call to `authContainer.handleWindowCallbackAsync()` before initializing `TelemetryLogger`.
2. **create-service-resolver.ts**
- Changed the third parameter of authContainer.registerAppAsync from false to true.
> fix(legacy-interopt): fixes missing call to handleWindowCallbackAsync

- .changeset/red-ducks-battle.md
- packages/modules/app/src/AppClient.ts
- Updated the `AppClient` class to modify the query path in the `fn` method for fetching app manifests:
- Changed the path from `/apps/${appKey}` to `/persons/me/apps/${appKey}`.
> Feat/module app/person specific manifest

- .changeset/tidy-buttons-clean.md
- packages/cli/src/bin/create-dev-serve.ts
- packages/cli/src/lib/plugins/app-proxy/app-proxy-plugin.ts
Added functionality for allow providing paths for `config`, `manifest` and bundle in `app-proxy-plugin`. This is useful for plugins that need to load resources from a specific path.
This was required since the AppClient was changed in [#2520](https://github.com/equinor/fusion-framework/pull/2520) which broke the ability to load resources from the plugin.
> feat: add configurable paths for app proxy plugin

- .changeset/sweet-keys-prove.md
- packages/react/legacy-interopt/src/LegacyAuthContainer.ts
- `packages/react/legacy-interopt/src/create-fusion-context.ts`
- `packages/react/legacy-interopt/src/create-service-resolver.ts`
1. **create-fusion-context.ts**
- Added a call to `authContainer.handleWindowCallbackAsync()` before initializing `TelemetryLogger`.
```ts
const authContainer = new LegacyAuthContainer({ auth: framework.modules.auth });
await authContainer.handleWindowCallbackAsync();
const telemetryLogger = new TelemetryLogger(telemetry?.instrumentationKey ?? '', authContainer);
```
2. **create-service-resolver.ts**
- Changed the third parameter of authContainer.registerAppAsync from false to true.
```ts
return authContainer.registerAppAsync(
id,
uris.map((x) => x.uri),
true,
);
```
> Fix/legacy interopt/token from url

- .changeset/lemon-coats-buy.md
- packages/react/modules/bookmark/src/useBookmark.ts
update import path for BookmarkCreateArgs in useBookmark
> fix: update import path for BookmarkCreateArgs in useBookmark

- .changeset/thin-baboons-doubt.md
- packages/cli/src/bin/dev-portal/AppLoader.tsx
Prevent mounting the app 2 times.
`AppLoader.tsx`
- Added import for last operator from rxjs/operators.
- Updated the initialize subscription to use the last operator.
> fix(cli): apploader only emits the latest result

- .changeset/wise-pears-cover.md
- packages/cli/src/lib/plugins/app-proxy/app-proxy-plugin.ts
- Stopped using node:path join in app-proxy-plugin since it caused issues on windows
> Fix/cli/dev proxy/join

- .changeset/pink-trees-visit.md
- packages/cli/src/bin/publish-application.ts
> fix(cli): resolve app key from manifest during publishing

- .changeset/rare-flies-talk.md
- packages/modules/services/src/bookmarks/endpoints/user-bookmark-favourite.head.ts
- packages/modules/services/src/bookmarks/selectors.ts
- packages/modules/services/src/provider.ts
Fixed `isBookmarkInFavorites` by altering `generateRequestParameters` which had a copy paste bug (wrong request method). Also disabled the `validate_api_request` response operation for now, it was throwing an error on all response code which waas not **OK**.
> in a future update, the `ResponseHandler` will provide the operators with the `Request` object, so they can access the request method and other request properties.
Also fixed the `headSelector` to only check response code, since a `HEAD` request does not return a body.
> fix(bookmarks): resolve request method issue and improve response handling

- .changeset/honest-grapes-deliver.md
- packages/cli/src/bin/create-dev-serve.ts
- packages/cli/src/bin/main.app.ts
Added `noOpen` option to the development server configuration.
**Modified files:**
- `packages/cli/src/bin/create-dev-serve.ts`
- `packages/cli/src/bin/main.app.ts`
**Changes:**
- Added `noOpen` boolean option to `createDevServer` function.
- Updated the server configuration to conditionally open the app in the default browser based on the `noOpen` option.
- Added `-n, --noOpen` option to the CLI command for starting the development server.
> feat(cli): adds option for --noOpen to not open dev-server in browser

- .changeset/little-carrots-kneel.md
- packages/modules/app/src/AppModuleProvider.ts
Added versioning support to `AppModuleProvider`.
**Modified files:**
- `packages/modules/app/src/AppModuleProvider.ts`
**Changes:**
- Imported `SemanticVersion` from `@equinor/fusion-framework-module`.
- Imported `version` from `./version`.
- Added a `version` getter to `AppModuleProvider` that returns a `SemanticVersion` instance.
> Fix/module app/set module version

- .changeset/flat-suns-brake.md
- cookbooks/app-react-settings/src/App.tsx
cookbook app-react-settings - setting label on fancy settings to fancy
> fix(app-react-settings) setting label on fancy settings to fancy

- .changeset/orange-ravens-care.md
- vue-press/src/guide/app/cli.md
- Update defineAppConfig function:
- Change scope to var in the environment object.
- Add scopes array to the api endpoint.
- Update configure function:
- Change configureClient to configureHttpClient.
- Update the configuration to include baseUri and defaultScopes.
- Update defineAppManifest function:
- Add version to the build object.
- Correct CLI command:
- Change app pack to app build-pack.
> chore: documentation update to cli under guides

- .changeset/gentle-fans-rule.md
- packages/utils/query/src/Query.ts
- packages/utils/query/src/cache/QueryCache.ts
- packages/utils/query/src/cache/actions.ts
- packages/utils/query/src/cache/create-reducer.ts
Allow rollback of cache setting.
When calling `mutate` the query will return a callback function which will set the state back to before the mutation happend
closes:
> feat(query): add callback for rollback of mutation on query cache

- .changeset/funny-bikes-provide.md
- .changeset/initial-release-ag-grid.md
- .changeset/seven-pans-watch.md
- cookbooks/app-react-ag-grid/app.manifest.config.ts
- cookbooks/app-react-ag-grid/package.json
- cookbooks/app-react-ag-grid/src/App.tsx
- cookbooks/app-react-ag-grid/src/config.ts
- cookbooks/app-react-ag-grid/tsconfig.json
- packages/modules/ag-grid/README.md
- packages/modules/ag-grid/package.json
- packages/modules/ag-grid/src/AgGridConfigurator.ts
- packages/modules/ag-grid/src/AgGridProvider.ts
- packages/modules/ag-grid/src/community.ts
- packages/modules/ag-grid/src/default-modules.ts
- packages/modules/ag-grid/src/enterprise.ts
- packages/modules/ag-grid/src/index.ts
- packages/modules/ag-grid/src/module.ts
- packages/modules/ag-grid/src/themes.ts
- packages/react/ag-grid/README.md
- packages/react/ag-grid/package.json
- packages/react/ag-grid/src/community.ts
- packages/react/ag-grid/src/enterprise.ts
- packages/react/ag-grid/src/index.ts
- packages/react/ag-grid/src/useTheme.ts
- packages/react/ag-grid/tsconfig.json
- pnpm-lock.yaml
This PR introduces updates and new features for the AG Grid integration with the Fusion Framework.
1. `@equinor/fusion-framework-module-ag-grid` will only require ag-grid as peer-dependency
2. `@equinor/fusion-framework-react-ag-grid` is a new module for using ag-grid in Fusion with React
3. Updated `@equinor/fusion-framework-cookbook-app-react-ag-grid` to test new behaviour and demonstrate usage
Currently, the AG Grid will:
1. Can fail to register modules because of three-shaking
4. Theme will throw error since `instanceof` check will fail
With this PR, the following changes are introduced:
- Updated `README.md` with detailed documentation for the AG Grid React for Fusion Framework, including installation, configuration, theming, customizing a grid instance, and upgrading from version 32 …
> Update AG Grid Integration and Documentation for Fusion Framework

- .changeset/cold-animals-tease.md
- biome.json
- packages/modules/navigation/src/lib/provider/NavigationProvider.ts
- packages/modules/navigation/src/navigator.ts
> refactor: Conform to Biome `linter.correctness.noVoidTypeReturn` and remove unnecessary return statements

- .changeset/odd-trees-wear.md
- packages/modules/msal/src/v2/provider.ts
add `defaultConfig` to `AuthProvider.createProxyProvider` for legacy child provider access.
closes:
> hotfix: msal auth provider

- .changeset/rude-mugs-dream.md
- packages/modules/ag-grid/src/themes.ts
Resolve a bug that prevented parts from being added to a newly created theme by ensuring the `parts` attribute is properly copied over during the cloning process.
> Fix theme cloning issue by copying parts to new theme

- .changeset/silent-apes-type.md
- packages/modules/app/src/AppClient.ts
Added `queueOperator: "merge"` to manifest and config in AppClient
closes: [AB#61485](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/61485)
> fix(framework): queueOperator

- .changeset/sad-trains-fix.md
- packages/cli/src/bin/dev-portal/useAppContextNavigation.ts
- packages/modules/context/src/ContextConfigBuilder.ts
- packages/modules/context/src/ContextProvider.ts
- packages/modules/context/src/configurator.ts
- packages/modules/services/tests/mocks/get-context-item.ts
**@equinor/fusion-framework-react:**
- Enhanced `useAppContextNavigation` to support custom context path extraction and generation. This allows for more flexible navigation handling based on application-specific requirements.
**@equinor/fusion-framework-module-context:**
- Added support for custom context path extraction and generation in `ContextConfigBuilder`, `ContextProvider`, and `ContextModuleConfigurator`.
- Introduced `setContextPathExtractor` and `setContextPathGenerator` methods in `ContextConfigBuilder` to allow developers to define custom logic for extracting and generating context paths.
- Updated `ContextProvider` to utilize `extractContextIdFromPath` and `generatePathFromContext` from the configuration, enabling dynamic path handling.
- Enhanced `ContextModuleConfigurator` …
> feat(context): add support for custom context path extraction and generation

- .changeset/whole-rice-jog.md
- packages/cli/src/bin/dev-portal/ContextSelector/useContextResolver.ts
- packages/react/app/src/create-component.tsx
- packages/react/app/src/make-component.tsx
- tsconfig.json
Also add env to 'onReactAppLoaded' event
Ref [AB#61787](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/61787)
closes:
> fix(cli): prevent context provider change if app is not current

- .changeset/deep-spiders-warn.md
- packages/react/framework/src/Framework.tsx
Introduce an optional parent `ModulesInstance` prop to the `Framework` component, allowing for enhanced module context management.
> Add optional parent ModulesInstance to Framework component

- .changeset/tasty-cities-relate.md
- packages/dev-portal/README.md
- packages/dev-portal/dev-server.ts
- packages/dev-portal/package.json
- packages/dev-portal/src/AppLoader.tsx
- packages/dev-portal/src/BookMarkSideSheet.tsx
- packages/dev-portal/src/ContextSelector/ContextSelector.tsx
- packages/dev-portal/src/ContextSelector/index.ts
- packages/dev-portal/src/ContextSelector/useContextResolver.ts
- packages/dev-portal/src/EquinorLoader.tsx
- packages/dev-portal/src/ErrorViewer.tsx
- packages/dev-portal/src/FusionLogo.tsx
- packages/dev-portal/src/Header.Actions.tsx
- packages/dev-portal/src/Header.tsx
- packages/dev-portal/src/PersonSideSheet/index.tsx
- packages/dev-portal/src/PersonSideSheet/sheets/FeatureSheetContent.tsx
- packages/dev-portal/src/PersonSideSheet/sheets/FeatureTogglerApp.tsx
- packages/dev-portal/src/PersonSideSheet/sheets/FeatureTogglerPortal.tsx
- packages/dev-portal/src/PersonSideSheet/sheets/LandingSheetContent.tsx
- packages/dev-portal/src/PersonSideSheet/sheets/Styled.tsx
- packages/dev-portal/src/PersonSideSheet/sheets/index.ts
- packages/dev-portal/src/PersonSideSheet/sheets/types.ts
- packages/dev-portal/src/Router.tsx
- packages/dev-portal/src/config.ts
- packages/dev-portal/src/main.tsx
- packages/dev-portal/src/resources/fallback-photo.svg.ts
- packages/dev-portal/src/useAppContextNavigation.ts
- packages/dev-portal/tsconfig.json
- pnpm-lock.yaml
Create a new package for the development portal, enhancing modularity and maintainability by separating functionality from the CLI. Include various components, loaders, and context selectors to support the development environment. Improve documentation and examples for user guidance.
> Introduce `@equinor/fusion-framework-dev-portal` package

- .changeset/four-carrots-shine.md
- packages/app/package.json
- packages/modules/ag-grid/package.json
- packages/modules/app/package.json
- packages/modules/bookmark/package.json
- packages/modules/event/package.json
- packages/modules/feature-flag/package.json
- packages/modules/http/package.json
- packages/modules/module/package.json
- packages/modules/msal/package.json
- packages/modules/navigation/package.json
- packages/modules/services/package.json
- packages/modules/signalr/package.json
- packages/modules/widget/package.json
- packages/react/ag-grid/package.json
- packages/react/app/package.json
- packages/react/framework/package.json
- packages/react/legacy-interopt/package.json
- packages/react/modules/bookmark/package.json
- packages/react/modules/signalr/package.json
- packages/utils/observable/package.json
- packages/utils/query/package.json
Removes unused typesVersions from package.json files
Cleans up package.json files by removing unnecessary
typesVersions entries that are no longer in use.
This refactor helps streamline the package configuration
and reduces potential confusion regarding type definitions.
closes:
> refactor: remove unused typesVersions from package.json files

- .changeset/all-rice-repair.md
- packages/utils/imports/package.json
- packages/utils/imports/src/error.ts
- packages/utils/imports/src/import-config.ts
- packages/utils/imports/src/import-script.ts
- packages/utils/imports/src/index.ts
- packages/utils/imports/src/resolve-config-file.ts
- packages/utils/imports/tests/import-config.test.ts
- packages/utils/imports/tests/setup.ts
- pnpm-lock.yaml
This update to `@equinor/fusion-imports` improves error handling, enhances support for resolving multiple configuration file base names, and delivers structured results for import operations. Key enhancements include:
- Dedicated error classes for file-related issues
- Improved handling of script imports
- Robust file resolution mechanisms
Import handling now supports resolving scripts with imports from other modules, correctly resolving from the source directory or node_modules. Previously, imports were resolved only from memory, excluding the current working directory (cwd).
Note: This release includes breaking changes, requiring updates to dependent codebases.
**Added:**
- Introduced `FileNotFoundError` and `FileNotAccessibleError` classes to handle specific file-related errors.
- …
> Improve import resolution and support for multiple configuration files

- .changeset/enhance-dotpath-utility.md
- packages/modules/module/src/BaseConfigBuilder.ts
- packages/modules/module/src/configurator.ts
- packages/modules/module/src/index.ts
- packages/modules/module/src/utils/dot-path.ts
- Improved the  utility to support deeper type resolution, including arrays and nominal class types.
- Updated  to use the new  and  types for better type safety and flexibility.
- Enhanced  in  to accept both direct values and callbacks, improving usability.
- Introduced and exported  type for better type safety in module configuration.
- Re-exported  in the public API for accessibility.
These changes improve type safety, developer experience, and flexibility when working with nested configurations and module builders.
closes:
> feat(framework): enhance DotPath utility and config builder flexibility

- .changeset/sse-support-added.md
- packages/modules/http/README.md
- packages/modules/http/src/errors.ts
- packages/modules/http/src/lib/client/client.ts
- packages/modules/http/src/lib/operators/sse.operator.ts
- packages/modules/http/src/lib/selectors/sse-selector.ts
- packages/modules/http/tests/sse.selector.test.ts
Introduce a new `sse$` method for subscribing to SSE streams, along with an `sseMap` operator for RxJS pipelines. Enhance error handling with a dedicated error class for SSE responses. Update documentation with examples for the new features.
> Add support for Server-Sent Events (SSE) in HTTP module

- .changeset/clear-keys-begin.md
- packages/modules/ag-grid/package.json
- packages/modules/context/package.json
- packages/modules/event/package.json
- packages/modules/module/package.json
- packages/modules/navigation/package.json
- packages/utils/observable/package.json
Enhance type resolution across multiple packages by updating the `typesVersions` field in the package.json files. This change improves the clarity and accessibility of type definitions.
> Update typesVersions in package.json for better type resolution

- .changeset/fix-to-observable-type.md
- packages/utils/observable/src/to-observable.ts
- packages/utils/observable/tests/observable.test.ts
- Improved the `DynamicInputValue` type in `to-observable.ts` to better support functions with arguments and ObservableInput return types.
- Updated the `toObservable` function signature for more accurate argument typing and handling.
- Renamed test file from `observable.ts` to `observable.test.ts` for consistency with test conventions.
- No breaking changes; all existing usages remain compatible.
> feat: enhance DynamicInputValue type and update toObservable function signature for improved argument handling

- .changeset/bright-buses-call.md
- packages/react/modules/bookmark/src/portal/useBookmarkNavigate.ts
update useBookmarkNavigate to trigger onCurrentBookmarkChanged 
closes:
> fix: update useBookmarkNavigate to trigger onCurrentBookmarkChanged 

- .changeset/wet-comics-tease.md
- packages/utils/observable/package.json
- packages/utils/observable/src/actions.ts
closes:
ReeAdd new export for actions in fusion-observable
> chore: add new export for actions in fusion-observable

- .changeset/stale-papayas-behave.md
- packages/modules/bookmark/src/BookmarkProvider.ts
When a user selects a bookmark, it becomes the current bookmark. However, if the user switches applications and later returns to activate the same bookmark, nothing happens—it is not triggered again. The only way to trigger it is by first selecting a different bookmark and then reselecting the original one. This behavior is unintuitive and problematic.
closes: [AB#63484](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/63484)
> fix(module-bookmark): allow reselection of the current bookmark by removing the existing check

- .changeset/chilly-clubs-talk.md
- packages/modules/bookmark/src/BookmarkProvider.ts
Remove unnecessary deepEqual check from the currentBookmark$ selector to ensure the current bookmark is always emitted, even when re-selected. This improves consistency and ensures consumers receive updates as expected.
closes:[AB#63505](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/63505)
> fix(bookmark): remove unnecessary deepEqual check from currentBookmark$ selector

- .changeset/good-pillows-ring.md
- packages/cli/src/bin/dev-portal/config.ts
closes:
correct HTTP client name from 'app' to 'apps' for service discovery alignment
> fix(FFC): correct HTTP client name from 'app' to 'apps' for service discovery alignment

- .changeset/tiny-clowns-cheer.md
- packages/modules/bookmark/src/index.ts
- packages/react/app/src/bookmark/useCurrentBookmark.ts
- packages/react/modules/bookmark/src/index.ts
- packages/react/modules/bookmark/src/useCurrentBookmark.ts
closes:
Update selector logic to only return a bookmark if its appKey matches the current app's appKey. This ensures bookmarks are correctly filtered and only relevant bookmarks are returned for the active application.
> fix(bookmark): update selector logic to filter bookmarks by current app's appKey

- .changeset/public-parts-poke.md
- packages/modules/bookmark/src/BookmarkProvider.reducer.ts
closes:
Enable MapSet in the bookmark module since a new Set is used in BookmarkState.
> fix(bookmark): Enable MapSet in the bookmark module since a new Set is used in BookmarkState

- .changeset/thick-swans-divide.md
- packages/react/app/src/help-center/useHelpCenter.ts
Added `openReleaseNotes` flag for `useHelpCenter` hook in `@equinor/fusion-framework-react-app`
closes:
[[Fusion-framework]: useHelpCenter for release notes](https://statoil-proview.visualstudio.com/Fusion%20Core/_workitems/edit/64722)
> fix(useHelpCenter): openReleaseNotes

- .changeset/cli-vite-config-refactor.md
- .changeset/dev-server-removed-tsconfig-paths.md
- packages/cli/package.json
- packages/cli/src/bin/app-dev.ts
- packages/cli/src/bin/helpers/load-vite-config.ts
- packages/cli/src/bin/portal-dev.ts
- packages/dev-server/package.json
- packages/dev-server/src/create-dev-server-config.ts
- pnpm-lock.yaml
The `@equinor/fusion-framework-dev-server` package includes the `vite-tsconfig-paths` plugin directly in its configuration, which provides TypeScript path resolution for development servers.
The responsibility for adding the `vite-tsconfig-paths` plugin has been moved to `@equinor/fusion-framework-cli`. The CLI now provides it via the `overrides` parameter in `createDevServerConfig`, ensuring consistent TypeScript path resolution in both development and build environments.
**Yes** - This is a breaking change for users who use `@equinor/fusion-framework-dev-server` outside of the CLI context. If you use the dev-server package directly, you must manually add the `vite-tsconfig-paths` plugin to your Vite config overrides to maintain the same TypeScript path resolution behavior.
- The …
> refactor(dev-server): move vite-tsconfig-paths responsibility to CLI

- .changeset/module_fixed-missing-type-definitions.md
- packages/modules/module/src/types.ts
The compiled TypeScript declaration files (types.d.ts) were missing type definitions that are referenced by public types, causing TypeScript compilation errors when consuming the module.
TypeScript consumers get compilation errors due to missing type definitions for  and  which are referenced by public types like  and .
All types referenced by public APIs are now available in the compiled declaration files, allowing TypeScript consumers to use the module without compilation errors.
No, this is a bug fix that only affects the TypeScript declaration files. No runtime behavior changes.
- Removed  JSDoc tags from  and 
- These utility types are now properly included in the public API since they are referenced by public types
- Updated section comment from "Internal helpers" to "Utility types" …
> fix(module): remove @internal tags from utility types referenced by public APIs

- .changeset/module-app_added-template-app-type.md
- packages/modules/app/src/types.ts
- Introduced 'template-app' as a new app type in the AppType union.
- This enhancement allows consumers to configure applications with template-based apps, expanding the available app types.
Updates the version for @equinor/fusion-framework-module-app to minor.
closes:
> feat(app): add 'template-app' to AppType union

- .changeset/cold-rabbits-tickle.md
- packages/modules/app/src/types.ts
Used in `fusion-portal`
closes:
> fix(app): add `landing-page` to union of `AppType`

- .github/workflows/pr-cleanup.yml
Potential fix for [https://github.com/equinor/fusion-framework/security/code-scanning/30](https://github.com/equinor/fusion-framework/security/code-scanning/30)
To fix the issue, you should add an explicit `permissions:` block to your workflow YAML to scope the GITHUB_TOKEN permissions as narrowly as possible. Since you are only checking out the code and (presumably) clearing a cache based on a branch, the minimal permission to start with is `contents: read`, unless `.github/workflows/actions/clear-cache` requires more.
- In `.github/workflows/pr-cleanup.yml`, directly under the `name:` field (typically at the top), add:
```yaml
permissions:
contents: read
```
This will set read-only access for repository contents for all jobs, unless a job overrides it. If the `clear-cache` action needs …
> Potential fix for code scanning alert no. 30: Workflow does not contain permissions

- .github/workflows/pre-release.yml
Potential fix for [https://github.com/equinor/fusion-framework/security/code-scanning/20](https://github.com/equinor/fusion-framework/security/code-scanning/20)
To fix this problem, explicitly set the minimum necessary `permissions` for the workflow or, if more granularity is needed, per-job. Since the main job here appears to be versioning or publishing packages, unless projects or steps require extra privileges, a minimally scoped permissions block should be used—typically, `contents: read` at the workflow or job level suffices unless publishing releases or creating pull requests, in which case additional permissions can be added as needed. For the broadest compatibility and minimal permissions, I'll add at the workflow root:
```yaml
permissions:
contents: read
```
This will protect …
> Potential fix for code scanning alert no. 20: Workflow does not contain permissions

- .github/workflows/cache.yml
- .github/workflows/ci.yml
This PR fixes an issue with PR #3409 which was merged with incomplete permissions.
- Bug fix
The cache workflow only has `contents: read` permission, but it uses `gh actions-cache delete` command which requires `actions: write` permission.
Added `actions: write` permission to allow the cache deletion operations to work properly.
No
- Follow-up to PR #3409 which was merged prematurely with insufficient permissions
- The cache workflow uses `gh actions-cache delete` command that requires `actions: write` permission
- Without this permission, cache management operations would fail
- Fixes insufficient permissions issue from PR #3409
---
> fix: add missing actions: write permission for cache workflow

- .github/workflows/pre-release.yml
This PR fixes an issue with PR #3407 which was merged with incomplete permissions.
- Bug fix
The pre-release workflow only has `contents: read` permission, but it needs to create changeset files, modify package.json files, and use GitHub tokens for changeset operations.
- Changed `contents: read` to `contents: write` for file modifications
- Added `id-token: write` for GitHub token operations
- Added comprehensive documentation and warnings about pre-release packages
No
- Follow-up to PR #3407 which was merged prematurely with insufficient permissions
- Pre-release workflow creates changeset files and modifies package.json files
- Added warnings that pre-release packages are experimental
- Added documentation explaining what the workflow does
- Fixes insufficient permissions issue from PR …
> fix: add missing write permissions for pre-release workflow

- .github/workflows/pr-cleanup.yml
This PR fixes an issue with PR #3406 which was merged with incomplete permissions.
- Bug fix
The pr-cleanup workflow only has `contents: read` permission, but it uses the clear-cache action which requires `actions: write` permission for cache deletion operations.
- Added `actions: write` permission for cache deletion operations
- Added comprehensive documentation explaining workflow purpose and permissions
- Clear breakdown of why each permission is needed
No
- Follow-up to PR #3406 which was merged prematurely with insufficient permissions
- pr-cleanup workflow cleans up cache entries when PRs are closed
- Uses clear-cache action which requires `actions: write` for `gh actions-cache delete` command
- Added documentation explaining the workflow's purpose and permission requirements
- …
> fix: add missing actions: write permission for pr-cleanup workflow

- .changeset/cli_improve-publish-docs.md
- packages/cli/docs/application.md
- packages/cli/docs/portal.md
- packages/cli/src/cli/commands/app/publish.ts
- packages/cli/src/cli/commands/portal/publish.ts
Documentation improvement
- App publish command documentation was misleading about when building occurs
- Portal publish command documentation was completely missing
- CLI source code had incorrect documentation about portal publish bundle parameter
- App publish command clearly explains conditional building behavior (builds only if no bundle provided)
- Portal publish command has complete documentation explaining it always builds
- CLI source code documentation matches actual command behavior
- Clear distinction between app and portal publish commands
No
This addresses the issue raised in https://github.com/equinor/fusion/issues/656 where users found the documentation misleading about the publish command behavior.
- fixes: #3417
- resolves: #3416  
- closes: …
> docs: improve publish command documentation clarity

- .changeset/dev-server_fix-options-cors-headers.md
- packages/dev-server/src/create-dev-server-config.ts
- Disabled Vite's internal CORS handling to allow backend services to manage OPTIONS requests correctly.
- Ensures proper forwarding of OPTIONS requests with necessary CORS headers, including Allow and Access-Control-Allow-Methods.
- Addresses the issue introduced after the Vite 7 update, improving compatibility with backend services.
closes: #3436
> fix: resolve issues for OPTIONS requests in dev server

- .changeset/cli-git-protocol-fix.md
- packages/cli/src/bin/helpers/ProjectTemplateRepository.ts
🐞 bug fix
When a user explicitly selects HTTPS protocol for Git cloning, the CLI still uses SSH if SSH configuration is detected on the system.
When HTTPS is explicitly selected, the CLI now properly uses HTTPS URLs regardless of SSH configuration availability.
No
Fixes: https://github.com/equinor/fusion-framework/issues/3462
closes:
> fix(cli): respect explicit HTTPS protocol selection

- .changeset/beige-sloths-judge.md
- packages/dev-portal/src/useAppContextNavigation.ts
Was introduced in #2930.
Removed in 8fffbfb12daa9748bf5290e5084cd4d409aed253 (cli next).
Ref #2930
Ref 8fffbfb12daa9748bf5290e5084cd4d409aed253
closes:
> fix(dev-portal): re-add support for custom context path extraction and generation

- .changeset/module-telemetry-added.md
- packages/modules/telemetry/README.md
- packages/modules/telemetry/package.json
- packages/modules/telemetry/src/Measurement.ts
- packages/modules/telemetry/src/TelemetryAdapter.ts
- packages/modules/telemetry/src/TelemetryConfigurator.interface.ts
- packages/modules/telemetry/src/TelemetryConfigurator.ts
- packages/modules/telemetry/src/TelemetryProvider.ts
- packages/modules/telemetry/src/__tests__/TelemetryConfigurator.test.ts
- packages/modules/telemetry/src/__tests__/TelemetryProvider.test.ts
- packages/modules/telemetry/src/adapters/application-insights/adapter.ts
- packages/modules/telemetry/src/adapters/console/adapter.ts
- packages/modules/telemetry/src/adapters/index.ts
- packages/modules/telemetry/src/index.ts
- packages/modules/telemetry/src/module.ts
- packages/modules/telemetry/src/static.ts
- packages/modules/telemetry/src/utils/resolve-metadata.ts
This PR introduces enhancements to the core telemetry module by adding comprehensive async initialization support.
The telemetry module currently initializes synchronously, which can block the application startup and doesn't handle adapter initialization failures gracefully.
The telemetry module now supports async initialization with:
- Async `initialize()` method on TelemetryProvider with Promise.allSettled error handling
- `initialized` property to track initialization state
- Individual error reporting for failed adapters without stopping the entire initialization process
- Enhanced BaseTelemetryAdapter with async initialization capabilities
- Application Insights adapter with async client setup
No, this is a backward-compatible enhancement. Existing synchronous usage continues to …
> feat: enhance telemetry module with async initialization support

- .changeset/framework-telemetry-integration.md
- packages/framework/package.json
- packages/framework/src/FrameworkConfigurator.ts
- packages/framework/src/__tests__/FrameworkConfigurator.test.ts
- packages/framework/src/index.ts
- packages/framework/src/init.ts
- packages/framework/src/types.ts
- packages/framework/tsconfig.json
- packages/framework/vitest.config.ts
- packages/modules/module/src/configurator.ts
- pnpm-lock.yaml
**What kind of change does this PR introduce?**  
Feature
**What is the current behavior?**  
Framework applications cannot easily enable telemetry through the configurator.
**What is the new behavior?**  
Framework applications can now configure telemetry in startup code with default configuration that includes framework metadata and event tracking.
**Does this PR introduce a breaking change?**  
No
**Other information?**  
This PR addresses TELE-205 by integrating telemetry into the Fusion Framework configurator. The changes include:
* Adding TelemetryModule to the framework core
* Default telemetry configuration with framework metadata
* Event prefixing for framework-specific events
* Public API for custom telemetry configuration
* Added tests for FrameworkConfigurator event prefixing …
> feat: Add telemetry support to framework configurator

- .changeset/vite-plugin-spa-telemetry-integration.md
- packages/vite-plugins/spa/package.json
- packages/vite-plugins/spa/src/html/bootstrap.ts
- packages/vite-plugins/spa/src/html/register-service-worker.ts
- packages/vite-plugins/spa/tsconfig.json
- pnpm-lock.yaml
This PR introduces a **feature** that adds comprehensive telemetry integration to the Vite SPA plugin.
Currently, the SPA plugin does not include any telemetry tracking or monitoring capabilities.
The SPA plugin now includes:
- Telemetry integration in the bootstrap process with ConsoleAdapter
- Performance tracking for portal loading operations  
- Service worker registration and token acquisition monitoring
- User metadata and portal configuration inclusion in telemetry
- Exception and error tracking throughout the SPA lifecycle
**Does this PR introduce a breaking change?**
No, this is a backward-compatible feature addition.
**Other information?**
This addresses the requirements in issue #3487 for adding telemetry to SPA applications and PWA functionality monitoring.
closes: #3487
- _I …
> feat(vite-plugins-spa): add comprehensive telemetry integration to SPA bootstrap and service worker

- .changeset/dev-portal-telemetry-integration.md
- .changeset/typescript-5-9-3-update.md
- .changeset/vite-plugin-spa-telemetry-integration.md
- packages/dev-server/README.md
- packages/dev-server/src/create-dev-server-config.ts
- packages/dev-server/src/types.ts
- packages/vite-plugins/spa/README.md
- packages/vite-plugins/spa/src/html/bootstrap.ts
- packages/vite-plugins/spa/src/types.ts
**What kind of change does this PR introduce?**
This PR introduces comprehensive telemetry integration across the SPA vite plugin and dev portal, along with type alignment fixes for the dev server.
**What is the current behavior?**
- SPA bootstrap lacks telemetry tracking for performance and error monitoring
- Dev portal has no telemetry integration for usage analytics
- Dev server types have JSDoc misalignment with optional SPA configuration
**What is the new behavior?**
- SPA bootstrap now includes telemetry with configurable console logging levels
- Dev portal has full telemetry integration with portal-specific metadata
- Dev server types are properly aligned with optional configuration
**Does this PR introduce a breaking change?**
No, this PR maintains backward compatibility. All …
> feat: add telemetry integration and dev server types alignment

- .changeset/cli-dev-server-config-docs.md
- .changeset/docs-dev-server-config-navigation.md
- .changeset/docs-telemetry-module.md
- packages/cli/docs/dev-server-config.md
- packages/cli/docs/dev-server.md
- packages/modules/telemetry/README.md
- packages/modules/telemetry/package.json
- vue-press/src/.vuepress/sidebar.ts
- vue-press/src/cli/docs/dev-server-config.md
- vue-press/src/modules/README.md
- vue-press/src/modules/telemetry/README.md
**What kind of change does this PR introduce?**
Documentation updates and dependency updates
**What is the current behavior?**
- Dev server documentation lacks configuration details
- Telemetry module is not documented in the modules list or sidebar
- Dependencies are using older versions
**What is the new behavior?**
- Added dev server configuration documentation with separate overview and config sections in sidebar
- Added telemetry module documentation and navigation
- Updated TypeScript from 5.9.2 to 5.9.3 and @types/node from 24.5.1 to 24.6.2
**Does this PR introduce a breaking change?**
No
**Other information?**
closes: #3523
> docs: add module-telemetry to modules list

- packages/modules/module/src/types.ts
This PR introduces a refactor to improve consistency between the ModuleEventLevel enum and the TelemetryLevel enum.
The ModuleEventLevel enum had values in a different order than TelemetryLevel, with NONE=0, Error=1, Warning=2, Information=3, Debug=4.
The enum now matches TelemetryLevel sequence: Debug=0, Information=1, Warning=2, Error=3, Critical=4. A new Critical level has been added as the highest severity.
No, this is a refactor that maintains the same enum structure and values, just reordered for consistency.
ref: #3483 #3490
> refactor: reorder ModuleEventLevel enum to match TelemetryLevel sequence

- .changeset/fix-capitalize-request-method-operator.md
- packages/modules/http/src/lib/operators/fetch-request.schema.ts
- packages/modules/http/tests/operators.test.ts
**What kind of change does this PR introduce?**
Bug fix
**What is the current behavior?**
The `capitalizeRequestMethodOperator` throws a Zod validation error when `request.method` is undefined, with the error message:
```
"Invalid input: expected string, received undefined"
```
**What is the new behavior?**
The operator now properly handles undefined HTTP method values without throwing validation errors.
**Does this PR introduce a breaking change?**
No
**Other information?**
This fix ensures the HTTP module operators work correctly in all scenarios, including when request methods are not explicitly set.
closes: #3539 (related to CLI version reporting, but this fixes a core HTTP operator issue)
> fix: capitalizeRequestMethodOperator to handle undefined HTTP methods

- .changeset/dependency-updates-person-components.md
- cookbooks/app-react-people/package.json
- packages/dev-portal/package.json
- packages/react/components/people-resolver/package.json
- pnpm-lock.yaml
Updated person component dependencies for improved functionality and bug fixes.
- Updated `@equinor/fusion-react-person` from `^0.10.3` to `^0.10.10` in app-react-people cookbook
- Updated `@equinor/fusion-wc-person` from `^3.1.8` to `^3.2.4` in dev-portal and people-resolver packages
> chore: update person component dependencies for improved functionality
